### ISSUE TITLE
Handle errors thrown by Intl formatters

### ISSUE THREAD

**Issue by stasm** [projectfluent/fluent.js#106]
In https://github.com/projectfluent/fluent.js/commit/cc32a1ec5608b2409132f2f0c0551106100d8cb5 we started catching errors thrown by Intl formatters inside of `FluentType`. Should we report them somehow?

**Comment by brettz9** [comment]
While you're at it (and I'm new to this, so just wrapping my head around your API now), would it not be useful to have a way of passing in options to the Intl formatters from the JavaScript API as opposed to only within the messages?

**Comment by zbraniecki** [comment]
@brettz9 please, take a look at the Fluent tutorial, section on Partial Arguments - http://projectfluent.org/fluent/guide/functions.html#partial-arguments

**Comment by stasm** [comment]
Fixed in #398 on the release branch.
