### ISSUE TITLE
Relationship with/Comparison to `Intl.MessageFormat` proposal?

### ISSUE THREAD

**Issue by brettz9** [projectfluent/fluent.js#117]
Hi,

I'd be curious to know how this project compares to the [Intl.MessageFormat](https://github.com/yahoo/intl-messageformat) proposal/library and whether it may be compatible (or intended to become compatible) and how the features of each compare, etc.?

Thanks!

**Comment by zbraniecki** [comment]
Hi, thank you for the question!

Please, take a look at our Wiki which has resources on this very topic: https://github.com/projectfluent/fluent/wiki/Fluent-and-ICU-MessageFormat

We intend to offer Fluent as an iterative improvement over MessageFormat and hence I would consider fluent.js implementation of the Fluent spec as an alternative to IntlMessageFormat library that you linked.

Please, let me know if that Wiki article and related ones answer your questions :)

**Comment by brettz9** [comment]
Sorry I hadn't come across that as I had only searched within this fluent.js repo... Will take a look and good to have the comparison--thanks very much! I guess I'll close then as having the info is what I needed...
