### ISSUE TITLE
Multiline comments

### ISSUE THREAD

**Issue by brettz9** [projectfluent/fluent.js#121]
Any reason multiline comments are not apparently supported?

**Comment by stasm** [comment]
Multiline comments should be supported. Have you run into troubles with them?

Note that Fluent Syntax 0.5 changes the comment sigil to `#` (https://github.com/projectfluent/fluent/issues/58).  The current versions of `fluent` and `fluent-syntax` only support the old syntax: `//`. The upcoming releases will support both sigils and later versions will drop the old syntax eventually.

http://projectfluent.org/play/ currently only supports the `//` comments.

**Comment by brettz9** [comment]
I'm just going by my overview of the tutorial which doesn't mention multiline comments by which I mean something like `/*` and `*/` which doesn't require intervening comment markers for each line. If such are supported (and if those are the markers in use), should I add that to the tutorial issue I filed (#120) and close this one?

**Comment by stasm** [comment]
Ah, I see. `/* … */` are not supported indeed. You need to prefix each line with `//` (Syntax 0.4 and before) or with `#` (Syntax 0.5).

**Comment by brettz9** [comment]
Ok, cool, but my intent in filing the issue is that for manually maintained files, particularly if one has translators not using IDEs or familiar with how to apply a comment to multiple lines, it seems it would be useful to be able to have a comment spread multiple lines without needing to apply them to each individual line.

**Comment by stasm** [comment]
Thanks for reporting this issue. If there are strong use-cases for multiline comments which don't require `#` on each line, please suggest the addition of this feature in the [Syntax Spec](https://github.com/projectfluent/fluent) repo, where all discussions about the syntax take place. `fluent.js` focuses on the JavaScript implementation of the spec, the bindings to DOM and front-end frameworks, and the tooling around it.
