### ISSUE TITLE
fluent-langneg and likelySubtags

### ISSUE THREAD

**Issue by brettz9** [projectfluent/fluent.js#122]
In https://github.com/projectfluent/fluent.js/blob/5379105b4e51b113c4bebc6f268ae314bcce8b4b/fluent-langneg/src/negotiate_languages.js#L95-L98 , you are passing likelySubtags as a fourth argument to `filterMatches`, but the imported `filterMatches` function (exported at https://github.com/projectfluent/fluent.js/blob/5379105b4e51b113c4bebc6f268ae314bcce8b4b/fluent-langneg/src/matches.js#L76-L78 ) does not accept a fourth argument (nor does it introspect on `arguments`).

**Comment by stasm** [comment]
@zbraniecki As the author of this code, would you like to take a look? Thanks!

**Comment by zbraniecki** [comment]
thanks! I'll fix it in the next release :)
