### ISSUE TITLE
Support CRLF as EOL

### ISSUE THREAD

**Issue by stasm** [projectfluent/fluent.js#131]
Currently the parser only supports LF as the EOL character. Any files created on Windows are broken unless special care is taken to change their EOLs.

**Comment by blushingpenguin** [comment]
If CR/CRLF are not supported as line endings, then the grammar should be updated as according to
[the syntax](https://github.com/projectfluent/fluent/blob/master/spec/fluent.ebnf) in the specification:

`
line_end            ::= "\u000D\u000A"
                      | "\u000A"
                      | "\u000D"
                      | EOF
`

**Comment by stasm** [comment]
There's an open issue in the grammar spec repo about making this call: .https://github.com/projectfluent/fluent/issues/154. Let's more the decision making over there.

**Comment by stasm** [comment]
https://github.com/projectfluent/fluent/issues/154 has been fixed. `CR` will no longer be a valid EOL when the Fluent Syntax Spec 0.7 is released in a few weeks. I think this means we can go back to discussing the implementation in `fluent.js`.

As per the Syntax spec, the supported line endings should be `LF` and `CRLF`. There's also an open issue about normalizing `CRLF` to `LF` in the AST (https://github.com/projectfluent/fluent/issues/163); it shoudn't affect the parsing behavior however.

**Comment by stasm** [comment]
Support for the `CRLF` line endings was added to the runtime and the tooling parsers in #287.
