### ISSUE TITLE
Using fluent with create-react-app throws error minifying /types.js file for production build

### ISSUE THREAD

**Issue by Ardhimas** [projectfluent/fluent.js#137]
Hello everyone,

I am currently working on an application that uses [create-react-app](https://github.com/facebook/create-react-app/tree/master), the most popular boilerplate for React applications. I discovered that my CI build on CircleCI was failing, and upon digging through the logs, I found this error that is reproducible locally by running `npm run build`:
```
Creating an optimized production build...
Failed to compile.

Failed to minify the code from this file:

 	./node_modules/fluent/src/types.js:10

Read more here: http://bit.ly/2tRViJ9
```

This is a known issue in create-react-app.

> Some third-party packages don't compile their code to ES5 before publishing to npm. This often causes problems in the ecosystem because neither browsers (except for most modern versions) nor some tools currently support all ES6 features. We recommend to publish code on npm as ES5 at least for a few more years.

>To resolve this:
Open an issue on the dependency's issue tracker and ask that the package be published pre-compiled.
Note: Create React App can consume both CommonJS and ES modules. For Node.js compatibility, it is recommended that the main entry point is CommonJS. However, they can optionally provide an ES module entry point with the module field in package.json. Note that even if a library provides an ES Modules version, it should still precompile other ES6 features to ES5 if it intends to support older browsers.
Fork the package and publish a corrected version yourself.

>If the dependency is small enough, copy it to your src/ folder and treat it as application code.

>In the future, we might start automatically compiling incompatible third-party modules, but it is not currently supported. This approach would also slow down the production builds.

[Read here](https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#npm-run-build-fails-to-minify)

I looked into the source for `src/types.js`, and sure enough it uses ES6 classes. As ES6 classes are simply a convenience wrapper around ES5 code, I think a simple transpile to ES5 for the code published to npm should do the trick. I know it's simple to do, but I'm not familiar with publishing multi-module repos to npm, so if someone else knows how to do this that would be great.

Thank you for reading, I hope this issue was helpful.

**Comment by stasm** [comment]
Thanks for the report! I also ran into this issue working on React apps. To mitigate it, `fluent` ships so-called `compat` builds transpiled to ES5. See the note in https://github.com/projectfluent/fluent.js/tree/master/fluent-react#compatibility. You'll need to use the `fluent/compat` package for Uglify to correctly minify the code. I'm eagerly waiting for `create-react-app` to switch to `babel-minify` :)

Do you have an opinion on which browsers the `compat` build should support? See #133 for some discussion about this.

Feel free to close this issue if using the `compat` builds solves the problem. Thanks again!

**Comment by Ardhimas** [comment]
@stasm Thank you for the prompt response. I actually was aware of the `compat` builds, but it did not occur to me use it. Perhaps it might be a good idea to put a small line along the lines of 
>For legacy browsers and build tools that can't use ES6 modules such as `create-react-app`, the compat build has been transpiled using Babel's env preset:`.

I can see another developer running into the same issue, and perhaps a few words may mitigate it in the future.

Thanks again.
