### ISSUE TITLE
Missing locale resource response causes syntax error

### ISSUE THREAD

**Issue by hkasemir** [projectfluent/fluent.js#138]
Steps to repro:

1. include a locale that you do not have a translation file for in your userLocales and availableLocales.
```js
const userLocales = ['en-US', 'fr'];
const availableLocales = ['en-US', 'fr'];

const currentLocales = negotiateLanguages(
  userLocales,
  availableLocales,
  defaultLocale
);

// in public/locales/ you have en-US.ftl but NOT fr.ftl
```
2. Localize a string without putting the localizationKey / message in the en-US.ftl
```js
// component.js
          <Localized id='cityNamePrompt'>
            <p styleName='bold'>City Name</p>
          </Localized>
```

3. A syntax error pops up in the developer console of the browser:
![image](https://user-images.githubusercontent.com/10947914/35597560-07e215e2-05d4-11e8-9f12-c1a7ea5aa4bb.png)

This is happening because when fetching the unavailable `fr.ftl` file, the public address returns an html response, which is then [parsed to text](https://github.com/projectfluent/fluent.js/blob/master/fluent-react/examples/async-messages/src/l10n.js#L12) and bundled with that locale's messages, obviously not in valid ftl format.

**Comment by stasm** [comment]
Thanks for the report! The error reporting done by `addMessages` needs some love for sure. I plan to work on updating the runtime FTL parser very soon; it will be an opportunity to improve error reporting as well.

I'm curious how that error made it to the console. It should have been caught inside of `addMessages`. Did you explicitly `console.log` the errors returned by it?

> when fetching the unavailable fr.ftl file, the public address returns an html response,

This doesn't sound right. Somewhere in your fetching code there should be a status check which throws or rejects the promise if the file is 404. If instead the HTML response is converted to text, it's hard to blame `addMessages` for trying to parse it :)

**Comment by hkasemir** [comment]
yup! I am logging the errors returned, as I felt it was prudent to do so in most cases.

Yea, I knew the thing producing the issue wasn't a problem with the fluent package suite itself, but the error message that came up wasn't helpful, and it felt like it could potentially be an issue that would come up with other devs as well. 🤷‍♀️

**Comment by zbraniecki** [comment]
@hkasemir do you plan to provide a patch for this?

**Comment by hkasemir** [comment]
no, I was not planning to. If you define desired behavior in this case and think it's an easy fix for me to resolve, then I'd be happy to work with you to provide a fix. But I think Stas and I agree that this not necessarily an issue with the package itself, and the ideal course of action here might be better error messaging.

**Comment by zbraniecki** [comment]
Ok, let's wait for stas then :)

**Comment by stasm** [comment]
Let's close this issue. The [Fluent Roadmap](https://github.com/projectfluent/fluent/wiki/Roadmap) for the first half of 2018 mentions error handling so we're sure this won't get lost in the future. Thanks again for filing.
