### ISSUE TITLE
Allow developers to create attribute filters for elements wrapped in <Localized>

### ISSUE THREAD

**Issue by stasm** [projectfluent/fluent.js#139]
Part of #103.

Right now `<Localized>` will apply all attributes found in the translation to the element wrapped inside of it. This may potentially override important props.

We should allow developers to control which attributes will be applied. For the initial release of overlays in `fluent-react` I think it's OK to err on the side of explicitness and _only allow_ attributes which are explicitly declared by the developer.

```properties
button = This button has a title attribute.
    .title = Title
    .other = This attribute will not be applied to the translation.
```

```jsx
<Localized id="button" attrs="title">
    <button>{'This button has a title attribute.'}</button>
</Localized>
```

What should be the type of the `attrs` prop?

  - A string, ssimilar to `className`: `attrs="title placeholder"`. 
  - An array: `attrs={["title", "placeholder"]}`.

**Comment by stasm** [comment]
@hkasemir, I think this will be useful for your extraction script. I saw you [relied on `data-l10n-attrs`](https://github.com/hkasemir/fluent-react-pull-strings/blob/fd741b131d9d296ccf4242297e765410549fae3f/index.js#L17) but that's specific to `fluent-dom`. For `fluent-react` we can do something more idiomatic :)

**Comment by hkasemir** [comment]
Very cool!
I would prefer an array.

**Comment by stasm** [comment]
Some time in the future we could build a list of good defaults, at least for the HTML elements. Something similar to `LOCALIZABLE_ATTRIBUTES` in `fluent-dom`.

https://github.com/projectfluent/fluent.js/blob/8c4afcca998d432752bbc6dd8350e554061cc30b/fluent-dom/src/overlay.js#L18-L42

With these defaults built into `fluent-react`, the `attrs` prop could amend the defaults on a per-element basis. We could use an object of boolean values where:

  - `true` means _allow this attribute even if it's forbidden by default_,
  - `false` means _forbid this attribute even if it's allowed by default_.

```jsx
<Localized id="input" attrs={{title: true, placeholder: false}}>
    <input placeholder="Not Localizable" />
</Localized>
```

**Comment by stasm** [comment]
That said, I don't see much of a use-case for forbidding an attribute that's allowed by default with `attrname: false`. The defaults should already be very conservative and safe. @Pike, @zbraniecki — do you have an opinion on this?

**Comment by zbraniecki** [comment]
I have not seen a good example where a default should be disallowed but then again, we mostly worked with HTML which has a standardized list. WC and React may not.

**Comment by hkasemir** [comment]
One thing that I have found particularly useful is that with react, the attributes have allowed for localizing props of react components that aren't anything like html. For example

```js
<Localized id="input" attrs={["description", "header"]}>
    <Widget
      header="Your Favorite Items"
      description="A list of things you've told us you like"
    />
</Localized>
```

How would this play into the 'allowed' list? As a dev, I really like this flexibility, rather than having to pass in localization IDs to the widget, or using `getString` for the props.

**Comment by stasm** [comment]
Yeah, I definitely agree that's useful. The default list of localizable attributes only makes sense for known HTML attributes. To @zbraniecki's point, for web components and React elements we simply can't know which attributes are localizable. It's a similar problem to the one `styled-components` have (_cf._ https://github.com/styled-components/styled-components/issues/439#issuecomment-276420364).

The HTML5 spec defines `title` an a few others as _global attributes_. It means they can be applied to any HTML element. This makes me think that `<Localized>` should by default allow `title` on any wrapped React element (HTML or not). Using an object as the value of `attrs` will make it possible to forbid localizing `title` with `attrs={{title: false}}` in some rare cases.

Here's your example rewritten to use an object as the value of `attrs`. I reads pretty clear to me.

```jsx
<Localized id="favorites_widget" attrs={{description: true, header: true}}>
    <Widget
      header="Your Favorite Items"
      description="A list of things you've told us you like"
    />
</Localized>
```

Using an object with attribute names as keys and booleans as values has two more advantages: 

  - it's explicit, and
  - it lends itself well to composition.

```jsx
import {Localized} from 'fluent-react';

function LocalizedWidget(props) {
    // `header` is a localizable attribute of Widget
    return <Localized {...props} attrs={{header: true, ...props.attrs}} />;
}

function MyApp(props) {
    // Forbid localizing `header` here just this once.
    return <LocalizedWidget attrs={{header: false}}> … </LocalizedWidget>;
}
```
