### ISSUE TITLE
Document fluent-dom's overlays

### ISSUE THREAD

**Issue by stasm** [projectfluent/fluent.js#153]
We should document how `fluent-dom`'s overlays work right now. It will make it easier to discuss the changes planned in #128 and #144. @zbraniecki Would you like to draft a first version of this?

Let's rename https://github.com/projectfluent/fluent.js/wiki/Overlays to `Overlays (fluent-react)` and create a new wiki page at `Overlays (fluent-dom)`.

Some documentation can be salvaged from the old [L20n DOM Overlays](https://github.com/l20n/spec/blob/master/dom-overlays.markdown) document.

The current implementation landed in #71 and #73. The commit messages and the bugs referenced should be helpful in writing the docs. Which I sadly can't say about #63 and #72. Let's learn from this and try to always land with good commit message explaining what changes and why.

**Comment by zbraniecki** [comment]
I took the first run at this with https://github.com/projectfluent/fluent.js/wiki/DOM-Overlays

**Comment by stasm** [comment]
Thanks, @zbraniecki. I edited the wiki page to match the implementation of DOM Overlays from `fluent-dom` 0.2.0`.
