### ISSUE TITLE
On Microsoft Edge the translated text has strange placeholder characters "FSI"/"PDI"

### ISSUE THREAD

**Issue by fernandogmar** [projectfluent/fluent.js#173]
I have created my own fluent loader for [System.js](https://github.com/systemjs/systemjs/blob/master/docs/creating-plugins.md) So ftl files can be instantiated on the fly... the thing is this works fine for all the browsers I have tested except for Edge... that it shows FSI and PDI characters.
Here they had the same issue (have a look for further details) https://github.com/mozilla/send/issues/476
But I still I don't get it working except  when I use to the brute force and just removing those characters when I got the final translation:
` unescape(escape(translated_text).replace(/%u2068|%u2069/g, ''));`

**Comment by flodolo** [comment]
Wait for someone who actually understands the code, but I assume you need `useIsolating`

There was a similar bug in Firefox https://bugzilla.mozilla.org/show_bug.cgi?id=1439018

**Comment by fernandogmar** [comment]
Thanks @flodolo ! That works for now

**Comment by zbraniecki** [comment]
@fernandogmar yeah, Microsoft has a bug in Edge (and Windows Platform) around it. The good news is that they fixed it in Edge. The bad news is that we're waiting for them to release the rs5 with the fix :)

For now, using `useIsolating=false` will "fix" it (but regress BiDi)

**Comment by zbraniecki** [comment]
I recently updated all my Windows installation to the October edition and it fixes the bug in Edge. I'm ok keeping this open temporarily, but I think we'll soon be able to close it.

**Comment by zbraniecki** [comment]
I'll take the liberty to close this now. Reopen if needed.
