### ISSUE TITLE
Don't set children for elements that can't have any

### ISSUE THREAD

**Issue by Gregoor** [projectfluent/fluent.js#174]
I'm wondering whether it'd be possible to have fluent-react not set an element's children depending on its type.

E.g. we had:
`<Localized id="wall-of-text-more-desktop" lineBreak={<br />}><p/></Localized>`

For which we had the string:
`bla bla <lineBreak> </lineBreak> bla`

As it accidentally contained a space, we got the following error:
`br is a void element tag and must neither have `children` nor use `dangerouslySetInnerHTML`.`

**Comment by zbraniecki** [comment]
@stasm - is that something we should triage?

**Comment by stasm** [comment]
I thought I fixed it in https://github.com/projectfluent/fluent.js/commit/68058119e5e9be9b0db05caaeae63356856dcbab and then in https://github.com/projectfluent/fluent.js/commit/6f1d6a8b2f918fadbdd3cc8999a858267637bc8f but actually, this one use-case is still broken. Thanks for filing the issue, @Gregoor.

We should make sure we're not setting any text content on void child elements. I'll fix this.
