### ISSUE TITLE
The use of <template> prevents server-side rendering

### ISSUE THREAD

**Issue by jamesreggio** [projectfluent/fluent.js#175]
For context, I'm trying to get `fluent-react` working within [Next.js](https://github.com/zeit/next.js/).

Next.js provides seamless server-side rendering of the React component hierarchy, which means that dependencies utilized during React rendering need to avoid dependencies upon the browser's runtime environment.

It appears that the only major issue preventing the use of Fluent during server-side rendering is the dependency upon the HTML `<template>` element within `fluent-react` for quick parsing of HTML. It'd be great if there was another approach that could do away with this lone dependency upon `document`.

**Comment by zbraniecki** [comment]
Would `DOMParser`[0] be an acceptable alternative? Also, is there no polyfill for `<template>`?

[0] https://developer.mozilla.org/en-US/docs/Web/API/DOMParser

**Comment by jamesreggio** [comment]
@zbraniecki — not quite. The problem here is during server-side rendering, which happenes in the absence of all DOM APIs. Every `template` polyfill I've found leverages some other DOM APIs, which are not available.

Conceivably, we could use [`xmldom`](https://www.npmjs.com/package/xmldom) as a server-side `DOMParser` implementation, and then use the built-in API in the browser.

**Comment by stasm** [comment]
There might be a way to allow passing custom markup sanitization functions to `<LocalizationProvider>`. I'll take a closer look at this in a week, when I'm back from vacation.

The code in `<Localized>` expects the parsed translation to have an interface of a `DocumentFragment`. Custom sanitization functions would still need to conform to this interface. On server-side, you could use `jsdom` to return a `DocumentFragment` with sanitized translation.

We actually use `jsdom` in our tests to be able to run them in node:

https://github.com/projectfluent/fluent.js/blob/b44b80205ae1dca0ed24e34d2e96842c4ee93550/fluent-react/test/__setup.js#L3-L13

Maybe you could do something similar in your app?

**Comment by stasm** [comment]
#229 has a proposed fix for this.

**Comment by stasm** [comment]
I closed #229 in favor of #233, also by @blushingpenguin. I think we might be able to land it today.

**Comment by stasm** [comment]
I just merged #233 which fixes this. Thanks, @blushingpenguin!

I need to fix a few more things before I publish a new version of `fluent-react`. The theme of this next version is _compatibility_ and it requires some changes in the core `fluent` package as well. I've created a [project board](https://github.com/projectfluent/fluent.js/projects/4) to track it.

**Comment by stasm** [comment]
I added some docs about the solution implemented in #233 at https://github.com/projectfluent/fluent.js/wiki/React-Overlays#custom-markup-parsers.
