### ISSUE TITLE
The use of generators is a build-tooling headache

### ISSUE THREAD

**Issue by jamesreggio** [projectfluent/fluent.js#176]
For context, I'm trying to get `fluent-react` working within [Next.js](https://github.com/zeit/next.js/).

Most web tooling assumes that the `main` file of any given `node_module` is suitable for execution as-is, and does not transpile or alter them when bundling.

It's clear with the `compat` variants of the Fluent.js packages that an effort has been made to provide ready-to-consume bundles. However, the fact that the main `fluent` package depends upon, yet excludes, the Regenerator runtime is a real headache, especially during server-side rendering. (With Next.js, it's not possible to load the Regenerator runtime on the server before the Fluent.js bundle is evaluated.)

I assume that Regenerator runtime was omitted from the bundle for size savings, and to avoid duplication. However, it would really help a ton if you included it (thereby making `compat` truly compatible right out of the box), or published another variant that included it.

**Comment by stasm** [comment]
Hey @jamesreggio, thanks for filing this issue and for your patience.

(I assume you specifically meant _async_ generators. Synchronous generators hopefully are well supported pretty much everywhere at this point.)

It's true that async generators may cause some build time issues. The regenerator runtime is not included in the `compat` build on purpose, however. If all dependencies which require it shipped with it, consumers would end up with a lot of duplicated code.

Depending on your compatibility story, you might not need the runtime—nor the `compat` builds. Newer Node versions and the evergreen browsers support async iteration. You'll still need to transpile JSX which requires making Babel understand the `for await` syntax. I think it should be possible to use the [syntax-async-generators](https://github.com/babel/babel/tree/6.x/packages/babel-plugin-syntax-async-generators) plugin for this purpose.

Let me know if this helps :)

https://github.com/babel/babel/tree/6.x/packages/babel-plugin-syntax-async-generators

**Comment by jamesreggio** [comment]
Nah, I meant just standard generators. IE11 doesn't support generators, and unfortunately, lots of web projects still need to support IE11.

I understand and can respect that you excluded `regenerator-runtime` from the `compat` builds to avoid duplication, so I'll just close this now. It's more a Next.js shortcoming that it doesn't provide a hook for requiring `regenerator-runtime` (or other polyfills) before loading Fluent. I'll continue to try to resolve on that end instead.

**Comment by jamesreggio** [comment]
As a post-scriptum, #175 is the most important problem blocking use with Next.js (or any server-side rendering technology), since the package depends upon DOM APIs.
