### ISSUE TITLE
fluent-react shouldn't force usage of fluent/compat

### ISSUE THREAD

**Issue by jimporter** [projectfluent/fluent.js#192]
As seen here:

https://github.com/projectfluent/fluent.js/blob/b44b80205ae1dca0ed24e34d2e96842c4ee93550/fluent-react/src/localization.js#L1

`fluent/compat` adds a polyfill for async generator functions, thus requiring projects to use `babel-polyfill` (or something like it), even if their browser supports async generators natively.

**Comment by stasm** [comment]
I would love to get rid of the import for `fluent/compat`. Last time I checked, it was still required to make `fluent-react` work with boilerplate generators like `create-react-app`. When I tried importing from non-transpiled `fluent`, the bundle built by `create-react-app`'s webpack included the un-transpiled code which broke the bundle's minification. This is a [known problem](https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#npm-run-build-fails-to-minify) of `create-react-app`.

Ideally, there would be a way to make that code import from `fluent` when using `fluent-react` and import from `fluent/compat` when using `fluent-react/compat`. I don't know if it would considered a hack, but we could literally just run `sed` when we create `fluent-react/compat`:

https://github.com/projectfluent/fluent.js/blob/b44b80205ae1dca0ed24e34d2e96842c4ee93550/fluent-react/makefile#L19-L27

**Comment by stasm** [comment]
Something like the following might do the trick, although it feels brittle:

```diff
diff --git a/fluent-react/makefile b/fluent-react/makefile
index 8c1cd59..f14ced6 100644
--- a/fluent-react/makefile
+++ b/fluent-react/makefile
@@ -1,11 +1,11 @@
 PACKAGE := fluent-react
 GLOBAL  := FluentReact
-DEPS    := fluent/compat:Fluent,react:React,prop-types:PropTypes
+DEPS    := fluent:Fluent,react:React,prop-types:PropTypes
 
 include ../common.mk
 
 build: $(PACKAGE).js compat.js
 
 $(PACKAGE).js: $(SOURCES)
 	@rollup $(CURDIR)/src/index.js \
 	    --config $(ROOT)/bundle_config.js \
@@ -19,13 +19,14 @@ $(PACKAGE).js: $(SOURCES)
 compat.js: $(SOURCES)
 	@rollup $(CURDIR)/src/index.js \
 	    --config $(ROOT)/compat_config.js \
 	    --banner "/* $(PACKAGE)@$(VERSION) */" \
 	    --amd.id $(PACKAGE) \
 	    --name $(GLOBAL) \
 	    --globals $(DEPS) \
 	    --output.file $@
+	@sed -i "s/'fluent'/'fluent\/compat'/" $@
 	@echo -e " $(OK) $@ built"
 
 clean:
 	@rm -f $(PACKAGE).js compat.js
 	@echo -e " $(OK) clean"
diff --git a/fluent-react/src/localization.js b/fluent-react/src/localization.js
index 91ca70e..7008948 100644
--- a/fluent-react/src/localization.js
+++ b/fluent-react/src/localization.js
@@ -1,9 +1,9 @@
-import { CachedIterable, mapContextSync } from "fluent/compat";
+import { CachedIterable, mapContextSync } from "fluent";
 
 /*
  * `ReactLocalization` handles translation formatting and fallback.
  *
  * The current negotiated fallback chain of languages is stored in the
  * `ReactLocalization` instance in form of an iterable of `MessageContext`
  * instances.  This iterable is used to find the best existing translation for
  * a given identifier.
```

**Comment by jimporter** [comment]
One option would be a Babel plugin that transforms `fluent` to `fluent/compat`. I couldn't find an existing one that did something like that, but it should be relatively straightforward to modify one to suit our purposes.

**Comment by jimporter** [comment]
Ah ha, looks like there *is* an already-existing Babel plugin for this: [`babel-plugin-transform-rename-import`](https://www.npmjs.com/package/babel-plugin-transform-rename-import). I don't know too much about how the `rollup` command works and how it talks to Babel, but this should be a lot less brittle than using `sed`, assuming we can get all the plumbing hooked up.

**Comment by stasm** [comment]
Ah, nice find, thanks! The plugin should do the job. I've been on PTO this week, I'll try it out on Monday.
