### ISSUE TITLE
Improve handling of non-deterministic resource insertions

### ISSUE THREAD

**Issue by zbraniecki** [projectfluent/fluent.js#199]
Currently, if any code tries to add a message ID to a context that already has this message ID registered, we're reporting an error and skipping this ID which means that the original ID stays in the context.

In #197 we discuss the consequences of non-deterministic resource additions to FluentDOM's Localization object.

We identified four possible approaches:

1) First wins, report error, skip overrides (current)
2) Last wins, report error
3) Throw on attempt to override
4) Remove old, don't add new, report error

**Comment by stasm** [comment]
In #332 we added the `allowOverrides` constructor option. The default behavior continues to be _first wins, report error, discard others_. When `allowOverrides` is set to `true`, the behavior changes to `last wins, report no errors`.

This doesn't completely solve the problem of adding resource in a non-deterministic manner, but I don't think the solution should be built into `FluentBundle`.  The calling code is much better suited to define its specific requirements and implement the strategy to enforce them. And with `allowOverrides` it has more control over how messages are added to the bundle.

I'm going to close this issue. Feel free to reopen if you think there's more to do here. Thanks!
