### ISSUE TITLE
Remove Node 6.9 support from fluent-syntax

### ISSUE THREAD

**Issue by stasm** [projectfluent/fluent.js#201]
We relaxed the engine requirement for `fluent-syntax` in #164. it shipped in `fluent-syntax` 0.6.5+ and 0.7.0. As of April 30, 2018, [Node 6 is no longer in _Active_ LTS cycle](https://github.com/nodejs/Release).

Starting from the yet-to-be-released `fluent-syntax` 0.8.0 I'd like to remove the support for Node 6.9.

@EnTeQuAk, have you started phasing out Node 6.9 support on your side?

**Comment by EnTeQuAk** [comment]
Please feel free to go ahead deprecating it!

I recently released a new version of `addons-linter` that pushes to node 8 and 10 as supported versions while the older linter version just keeps using the older fluent library but we generally aim for node 8 now.

Thanks a lot for relaxing this back then!

**Comment by stasm** [comment]
That's great news, thanks @EnTeQuAk! Happy that it all worked out.
