### ISSUE TITLE
requiring "fluent" fails on node <10

### ISSUE THREAD

**Issue by k88hudson** [projectfluent/fluent.js#207]
Not sure if this expected but if I install `fluent`(0.6.4) with npm and try to `require("fluent")` in node 8 or 9, I get a syntax error due to the use of async iterators/`for await...of`

AFAIK async iterators are only supported as of node 10, but your target appears to be node 8?

**Comment by stasm** [comment]
I wasn't sure how to express this in the `package.json`, but the Node 8.9 support is for the `compat` builds. `require("fluent/compat")` should do the trick as long as you also use `babel-polyfill` to provide the `regeneratorRuntime`. Sorry for the trouble!

**Comment by k88hudson** [comment]
ah, ok. thanks :+1:
