### ISSUE TITLE
fluent: Implement Syntax 0.6 in js runtime

### ISSUE THREAD

**Issue by Pike** [projectfluent/fluent.js#216]
Keeping track of changes in fluent 0.6 that could/should be implemented in fluent runtime

- [x] `ExternalArgument` -> `VariableReference`
- [DROPPED] Add `TermReference`
- [DROPPED] (Maybe?) Add `VariantList`
    - The current parser/resolver should parse `VariantLists` as `Patterns` with a selector-less `SelectExpression`. It may be OK to keep it this way for now.

**Comment by stasm** [comment]
Hey @zbraniecki, this is the issue about implementing Syntax 0.6 in the runtime parser and resolver. We talked about it yesterday. Let me know if you'd like to take some of the items listed in the description (I added a few more). If not, that's cool, I'll have time early next week to work on this. Thanks!

**Comment by stasm** [comment]
This landed in master last week and was published as `fluent` 0.7.0.
