### ISSUE TITLE
failing test in fluent

### ISSUE THREAD

**Issue by mdw211** [projectfluent/fluent.js#227]
I've tried this using ubuntu 16.04 on lxss and ubuntu 18.04 on real hardware:

  233 passing (101ms)
  5 pending
  1 failing

  1) Structure tests
       message_with_empty_pattern.ftl:

      AssertionError [ERR_ASSERTION]: Actual Annotations don't match the expected ones
      + expected - actual

           "attrs": {
             "attr": "Attr"
           }
         }
      +  "key5": ""
       }
      
      at Context.<anonymous> (test/parser_structure_test.js:32:16)
      at <anonymous>

**Comment by mdw211** [comment]
sorry, ignore this, i must have had some local changes causing the test to fail

**Comment by stasm** [comment]
I'm happy to hear that it works :)
