### ISSUE TITLE
Cannot use fluent-web examples

### ISSUE THREAD

**Issue by rahul-thakoor** [projectfluent/fluent.js#234]
Hello there!
I am trying to run the examples in `fluent-web` but I am getting some errors:
```console
fluent-web.js:3246 Uncaught (in promise) TypeError: ctx.hasMessage is not a function
    at keys.forEach (fluent-web.js:3246)
    at Array.forEach (<anonymous>)
    at keysFromContext (fluent-web.js:3241)
    at DOMLocalization.formatWithFallback (fluent-web.js:3032)
```
I am assuming that I can run the examples in a web browser without using node. I took the following steps to run the examples:
1. Clone the `fluent.js` repo
2. Run `npm install` at the root level of the cloned project
3. Run `make deps`
4. Run `make`where all the build processes where successful

I am using MAMP to serve the project. 
Any help is much appreciated. Thanks

**Comment by markwestcott34** [comment]
Just wondering if there is any timeframe on this? Would like to migrate from l20n.js to fluent but suffering from this same issue. Thanks :)

**Comment by zbraniecki** [comment]
Thanks for the poke! I updated fluent-web to the latest Fluent and FluentDOM. You should be able to clone from https://github.com/projectfluent/fluent-web then `npm i` (and maybe rollup-cli?) and `make build`. The result `examples/index.html` should work now!

I'll maintain it and try to improve the build process but all patches are welcomed!
