### ISSUE TITLE
fluent-dom 0.3.0 is broken with latest fluent release

### ISSUE THREAD

**Issue by mathroc** [projectfluent/fluent.js#238]
> warning  in ./node_modules/fluent-dom/src/localization.js
> "export 'CachedAsyncIterable' was not found in '../../fluent/src/index'

in #191 some code was moved into the `fluent` package but there's not been a release for it yet

**Comment by stasm** [comment]
Thanks for the report! I started cleaning this up and moved `CachedIterables` into a separate package: [cached-iterable](https://github.com/projectfluent/cached-iterable). The next release of `fluent-dom` will use it as a dependency.

**Comment by zbraniecki** [comment]
I released 0.4.0 which uses CachedIterable - https://github.com/projectfluent/fluent.js/releases/tag/fluent-dom%400.4.0
