### ISSUE TITLE
Repository managment

### ISSUE THREAD

**Issue by romulocintra** [projectfluent/fluent.js#275]
Suggest use a tool like https://lernajs.io/ . to manage this "Monorepo" , it would make some things simpler , install packages , transitional/Circular dependency managment , and unify build/publish processes , changelog etc ...

**Comment by stasm** [comment]
I'd love that, but so far I've been busy with other work and I couldn't justify taking the time to look into using Lerna. I'd love to get some help with this :)

**Comment by romulocintra** [comment]
I can take this one , it will depend on my free time but not being urgent i can give it some love and also work on some processes you have that look very manual 👍  you can assign it to me

**Comment by romulocintra** [comment]
@stasm  , perfect  i will only progress to have same state you have actually with your scripts , at moment i have some failing tests but are the same ones that are failing with your actual build. 

for now i will keep it just as WIP and also think in some strategy to accomplish the #274 .

Thks for your time

**Comment by macabeus** [comment]
Maybe [Yarn Workspace](https://classic.yarnpkg.com/en/docs/workspaces/) would be enough and easer to use than Lerna?
I'm using Yarn Workspace a lot on my projects, and it's work very pretty.

Yarn 2 has better features for workspace, but unfortunately it isn't work with TS.

**Comment by macabeus** [comment]
@stasm @romulocintra  Maybe [Yarn Workspace](https://classic.yarnpkg.com/en/docs/workspaces/) would be enough and easer to use than Lerna?
I'm using Yarn Workspace a lot on my projects, and it's work very pretty.

Yarn 2 has better features for workspace, but unfortunately it isn't work with TS.

**Comment by romulocintra** [comment]
> @stasm @romulocintra Maybe [Yarn Workspace](https://classic.yarnpkg.com/en/docs/workspaces/) would be enough and easer to use than Lerna?
> I'm using Yarn Workspace a lot on my projects, and it's work very pretty.
> 
> Yarn 2 has better features for workspace, but unfortunately it isn't work with TS.

Few time ago i did a little benchmark running fluent modules using lerna and actual setup was faster. Yarn workspaces would be a good alternative too... but to be honest i was surprised by the speed compared with lerna back on time.

**Comment by eemeli** [comment]
Closing as #569 was merged.
