### ISSUE TITLE
SyntaxError: Unexpected token )   fluent-syntax.js:1504

### ISSUE THREAD

**Issue by hkasemir** [projectfluent/fluent.js#283]
I noticed this after updating to fluent-syntax 0.8.1 in a project that uses webpack to build. It's strange because I also imported it into a different project with a similar build system, and it was fine there, so I'm not sure why it failed in this specific case.

The block of code it's referring to is
```js
        return new CallExpression(
          func,
          args.positional,
          args.named,
        );
```

and I found that if I removed the trailing comma after the last arg, that the error went away and everything was fine. 🤷‍♀️ reporting here, because it's weird, and also, it means that unless that trailing comma goes away, I might not be able to deploy this one project with the updated fluent-syntax package.

full error:

```
.../node_modules/fluent-syntax/fluent-syntax.js:1504
        );
        ^

SyntaxError: Unexpected token )
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/heidi/projects/udacity/uconnect-admin/src/app/helpers/ast-helper.js:1:78)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
```

**Comment by Pike** [comment]
Thanks for updating your deployments, and the investigation here.

Is this something that you could fix by upgrading the build toolchain?

stas left some open PRs that also include webpack (I think) in https://github.com/pulls?q=is%3Aopen+is%3Apr+author%3Astasm+archived%3Afalse+user%3Amozilla. As you mentioned, sometimes it works :-/

As for this particular issue, trailing comma in multiline args is quite liked by some. I'm not comfortable making a decision either way while stas is on PTO, so changing this might take two more weeks.

**Comment by hkasemir** [comment]
Luckily this is not a blocking issue, because the project that is experiencing the error is being sunsetted, so updating fluent is not high priority for it, and there doesn't seem to be an error in the other build that we are using it in, so it's unclear why it works in one and not the other - and I'm not highly motivated to debug it.

I understand the preference for comma dangles in objects, but I could see it being more confusing in function argument lists, and especially if it causes syntax errors for some users, it's a simple stylistic choice that could be updated.

**Comment by stasm** [comment]
This is a question about our compatibility strategy. The rule I'd like us to stick to is to allow any current stable ES syntax in the code (i.e. up to ES2018 as of this writing) in the regular builds, and to downgrade to a [slightly less modern syntax](https://discourse.mozilla.org/t/re-defining-the-browser-support-matrix-for-fluent-js/29364) in the `compat` builds (but still pretty modern; bye bye IE11).

Trailing commas in function parameters were [standardized in ES 2017](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Trailing_commas#Trailing_commas_in_functions). I don't really mind using (or not using) them. What I care about mostly here is to be consistent in deciding what can be used and which syntax should be avoided.

Have you tried using `fluent-syntax/compat`?

**Comment by hkasemir** [comment]
sounds good!

**Comment by drdgvhbh** [comment]
This doesn't really work if this package is a transitive dependency. I.e. the i18next fluent package depends on this package.

https://github.com/i18next/i18next-fluent
