### ISSUE TITLE
Allow <Localized> to wrap a text node?

### ISSUE THREAD

**Issue by birtles** [projectfluent/fluent.js#285]
This might be a silly request, I'm not familiar with fluent-react and haven't really thought it through, but would it make sense to allow `<Localized>` to wrap a text node instead of just a React element?

I notice Localized currently uses React's [`children.only`](https://github.com/projectfluent/fluent.js/blob/f0eb0983bacccdf59086215e856e1181c8be70fc/fluent-react/src/localized.js#L83) which requires a single React _element_ child.

We're using fluent-react in the rewrite of Firefox's remote debugging and noticed we had to add extra `<span>` elements so I went to investigate why. I suppose supporting text nodes would add extra complexity to the `render()` method of `Localized` but I thought I would ask anyway.

**Comment by stasm** [comment]
Thanks for asking! I can definitely see the value in allowing text nodes inside of `Localized`. We have an open PR #230 about this. @blushingpenguin did you want to finish that PR or would you like me to take over?

**Comment by blushingpenguin** [comment]
Yes, I'd got a bit distracted from those things!  I can sort it on Monday, but feel free to take over if you want it sooner.

**Comment by birtles** [comment]
Great, thank you both!

**Comment by stasm** [comment]
#230 fixed this; closing. I'll publish a new release of `fluent-react` this week.
