### ISSUE TITLE
Deprecate fluent-intl-polyfill

### ISSUE THREAD

**Issue by stasm** [projectfluent/fluent.js#293]
Let's just recommend using [intl-pluralrules](https://www.npmjs.com/package/intl-pluralrules).

**Comment by eemeli** [comment]
This may be of particular interest as a little while ago I [released version 1.0.0](https://github.com/eemeli/intl-pluralrules/releases) of `intl-pluralrules`, which provides full support of the current spec.

**Comment by stasm** [comment]
Yep, thank you for adding the support for `minimumFractionDigits ` and friends :) Great work! I'll switch to using it in the example code and in docs.

**Comment by stasm** [comment]
I added the deprecation notice to https://www.npmjs.com/package/fluent-intl-polyfill. I also filed #407 to remove the code from the repo.

**Comment by stasm** [comment]
And I archived the https://github.com/projectfluent/IntlPluralRules/tree/module repo, which I had created back in the day to work around some packaging problems which don't exist in 2019.

**Comment by stasm** [comment]
#407 has been merged to master. Let's close this issue now.
