### ISSUE TITLE
DOMLocalization can cause attribute churn by removing and re-adding attributes with the same value they had before removal

### ISSUE THREAD

**Issue by bgrins** [projectfluent/fluent.js#300]
I noticed this when looking into perf in https://bugzilla.mozilla.org/show_bug.cgi?id=1448213. We occasionally hit a case where an attribute gets removed and then re-added with the same value: https://searchfox.org/mozilla-central/rev/8848b9741fc4ee4e9bc3ae83ea0fc048da39979f/intl/l10n/DOMLocalization.jsm#170-189. This can cause issues where, for instance, we underline an accesskey in a label, and then un-underline it, and then re-underline it to the same value.

I notice this happens on `<button id="useCurrentBtn">` in about:preferences as an example.

**Comment by stasm** [comment]
Thanks for filing this here. Would it help if we compared the existing values of localizable attributes before setting new values, or is there anything more to keep in mind here?

**Comment by bgrins** [comment]
I think comparing existing values would be enough.

**Comment by asurkov** [comment]
> I noticed this when looking into perf in https://bugzilla.mozilla.org/show_bug.cgi?id=1448213. We occasionally hit a case where an attribute gets removed and then re-added with the same value: https://searchfox.org/mozilla-central/rev/8848b9741fc4ee4e9bc3ae83ea0fc048da39979f/intl/l10n/DOMLocalization.jsm#170-189. 

@bgrins  do you say that overlayAttributes is called for no-change? I assume that @data-l10n-attrs is pretty static, i.e. never changed once set.

**Comment by bgrins** [comment]
See https://bugzilla.mozilla.org/show_bug.cgi?id=1534480, which has a patch that handles both data-l10n-attrs and individual attributes in overlayAttributes.

**Comment by Pike** [comment]
Is this fixed by #354 ? @zbraniecki ?

**Comment by zbraniecki** [comment]
yes!
