### ISSUE TITLE
Remove behavior tests

### ISSUE THREAD

**Issue by stasm** [projectfluent/fluent.js#304]
I'm having trouble understanding the role of the behavior tests. I seem to remember that they were supposed to make it easy to write down expected error messages. However, writing or editing right now is far from easy and I usually just run them, let them fail, and then hand edit the errors and positions based on the actual output of the tests.

It's also usually unclear to me which tests should be written as behavior tests and which—as structure tests. I think I'd like to remove behavior tests altogether.

Practically, it would be best to review the existing behavior tests in [fluent-syntax/test/fixtures_behavior](https://github.com/projectfluent/fluent.js/tree/6edf2768952101aabed3578f46cc504f5940745e/fluent-syntax/test/fixtures_behavior) and move some of them into structure fixtures. There's already a convention in the structure fixtures of putting a comment next to messages which are expected to fail. We could enforce it by verifying that every `Junk` in the JSONs is preceded by a comment with `ERROR` in it. I'm slightly afraid of some edge-cases where the presence of the `ERROR` comment could influence the result of parsing, but I'd like to try it and see if it works.

Note that this would be different from the [preprocessing step](https://github.com/projectfluent/fluent.js/blob/6edf2768952101aabed3578f46cc504f5940745e/fluent-syntax/test/behavior_test.js) used in behavior tests, which removes these lines from the test files before they're parsed (which is why they need to include the positions).

Behavior fixtures are also used in the runtime implementation: [fluent/test/fixtures_behavior](https://github.com/projectfluent/fluent.js/tree/6edf2768952101aabed3578f46cc504f5940745e/fluent/test/fixtures_behavior). Because the AST are different between the tooling and the runtime parser, the [test only compares](https://github.com/projectfluent/fluent.js/blob/6edf2768952101aabed3578f46cc504f5940745e/fluent/test/parser_behavior_test.js#L36-L56) if the runtime parser parsed the value and the attributes of each message and term. The actual contents are ignored. We can still rely on the runtime structure tests which test the same thing and much more.

@Pike, @zbraniecki: you were both involved in the creation of behavior tests. Do you have thoughts on this?

**Comment by stasm** [comment]
I also filed #305 to clean up the structure tests.

**Comment by Pike** [comment]
I don't recall their inception. I'm pretty sure that I don't know what their original distinction from structure tests is, and how that plays out today. Zibi?

 I do recall that I had trouble pinpointing the error locations. But that could probably be addressed by chunking the content in the test files, so that error positions are relative to the chunk and not to the stripped file.

**Comment by stasm** [comment]
This was fixed in #347, first on the `zeronine` branch, and then on master.
