### ISSUE TITLE
Clean up tooling parser around `getLiteral`

### ISSUE THREAD

**Issue by Pike** [projectfluent/fluent.js#315]
In reviewing #311, I found that `getLiteral` and `getSelectorExpression` are just very confusing.

For one, `getLiteral` doesn't do what it says, but then it also returns, in order, a ref, a ref, a literal, a ref and finally a literal again. Trying to find out what that code actually returns, and what of that's left over at which point in `getSelectorExpression` ... took me a while.

My ad-hoc proposal is to just rip out `getLiteral` entirely, and fold it in to `getSelectorExpression`.

I'd expect the code to be easier to read, in particular if we'd add a comment or two.

And we don't need to figure out a name for `getLiteral` if we'd keep it and make it do literals and non-literals in order.

**Comment by stasm** [comment]
Great suggestion. `getLiteral` is only used in `getSelectorExpression` anyways. Folding into it will make the early returns easier to make, well, early.

P.S. Let's rename `getSelectorExpression` to `getInlineExpression` along the way, too.

**Comment by stasm** [comment]
#318 landed on `zeroeight` and I think we can mark this as fixed. There are more improvements which will be made possible once https://github.com/projectfluent/fluent/pull/221 lands in the spec.
