### ISSUE TITLE
Installing `fluent-dom`, from npm, doesn't work

### ISSUE THREAD

**Issue by Snuffleupagus** [projectfluent/fluent.js#321]
*I was attempting to, very briefly, look into https://github.com/mozilla/pdf.js/issues/10075.*

**STR:**
 - Install `fluent-dom`, using the `npm install fluent-dom` command as outlined in https://github.com/projectfluent/fluent.js/blob/master/fluent-dom/README.md#installation

 - Attempt to `import { DOMLocalization } from 'fluent-dom';` as outlined in https://github.com/projectfluent/fluent.js/blob/master/fluent-dom/README.md#how-to-use.

**ER:**
`fluent-dom` is correctly imported, and can be used.

**AR:**
`fluent-dom` cannot be imported, since no `fluent-dom.js` file can be found in the `node_modules/fluent-dom` directory.

---

It would appear, at least to me, that the `fluent-dom` library was perhaps not built correctly (prior to uploading it npm), given that the contents of the `node_modules/fluent-dom/` directory looks (basically) identical to the source as found in https://github.com/projectfluent/fluent.js/tree/master/fluent-dom; please see
![dom](https://user-images.githubusercontent.com/2692120/49521339-86d1f880-f8a5-11e8-873e-5bbdc3948929.png)

---

For comparison, the `npm install fluent` command works fine and the `node_modules/fluent/` folder obtained has a more "expected" structure; please see
![base](https://user-images.githubusercontent.com/2692120/49521782-766e4d80-f8a6-11e8-8aad-413d7b9b385a.png)

**Comment by zbraniecki** [comment]
Fixed in fluent-dom 0.4.1 - https://github.com/projectfluent/fluent.js/commit/0f59f3b947b41b15a513dda3596e9b53b44cc6bd
