### ISSUE TITLE
TypeScript definitions

### ISSUE THREAD

**Issue by huy-nguyen** [projectfluent/fluent.js#329]
I'm using fluent and quite like it. However, the project currently has no TypeScript definitions and I can create them if the maintainers so desire.

**Comment by Gregoor** [comment]
That's great, I've been meaning to do that for a while. We have some basic typings for fluent-react over at the Common Voice repo: https://github.com/mozilla/voice-web/blob/master/web/src/fluent-react.d.ts
Maybe this helps as a starting point.

**Comment by huy-nguyen** [comment]
I've opened a PR for `fluent`, `fluent-react` and `fluent-langneg` at https://github.com/DefinitelyTyped/DefinitelyTyped/pull/32235 if you wan to take a look. The files ending in `-tests` are examples of user-facing API to be tested against the type definitions. I didn't make the definitions for other packages because they don't seem to be user-facing.

**Comment by JamesNimlos** [comment]
I think this issue can be closed now seeing as the referenced definitions have been merged, as well as typedefs for the new versions were merged in DefinitelyTyped/DefinitelyTyped#40179

**Comment by stasm** [comment]
Yes, thanks!

I've also made good progress in #376 in which I migrated `@fluent/bundle` to TypeScript.  When the PR lands, type definitions will become easy to manage (and will move to this repo). If all goes well, other `@fluent/` packages will follow later this year.
