### ISSUE TITLE
langneg: add Accept-Language header parsing support

### ISSUE THREAD

**Issue by 6a68** [projectfluent/fluent.js#34]
Since fluent-langneg runs on both server and client, it would be nice to not have to separately parse the Accept-Language header string into an array of locales:

```js
negotiateLanguages(req.header('Accept-Language'), availableLocales)
```

As things stand, I've either got to add another language negotiation library, like accept-language-parser, or roll my own, probably buggy, regex to do the job ;-)

**Comment by zbraniecki** [comment]
So, all we'll want to do here is parse Accept-Language syntax and create a list out of it, right?

**Comment by stasm** [comment]
Why is using an existing parser a bad idea?

**Comment by zbraniecki** [comment]
It's not. It just adds another dependency as far as I understand.
I looked through npmjs and there doesn't seem to be a good library for parsing accept-languages string into a list of BCP47 language tags.
Which means that using any library (the closes I found is https://www.npmjs.com/package/accept-language-parser ) will require you to manually construct language tags from language/region pair, and I'm not sure how it handles script and variant.

**Comment by stasm** [comment]
I don't see additional dependencies as a problem, tbh. OTOH, if there are no good solution out there, let's fix this.  The semantics of q-values might require some additional logic: https://developer.mozilla.org/en-US/docs/Glossary/Quality_values

My suggestion would be to offer a parser as a helper export on the `fluent-langneg` module. This has two advantages:

  - `negotiateLanguages` can still accept an array of requested locales and we don't have to make special cases for when the argument is an `Accept-Language` string,

  - client-side consumers won't need the export and good bundlers will tree-shake it.

@zbraniecki, do you want to work on this?

**Comment by zbraniecki** [comment]
yeah!
