### ISSUE TITLE
Require Node.js 10

### ISSUE THREAD

**Issue by stasm** [projectfluent/fluent.js#341]
All `fluent.js` packages currently require `node >= 8.9.0`, which ceased to be the active LTS as of January 2019. The new LTS is Node.js 10 which will remain active until April 2020. See https://github.com/nodejs/Release.

Node.js 10 ships with a native implementation of `Intl.PluralRules`. We currently use an [outdated polyfill](https://www.npmjs.com/package/intl-pluralrules) which diverges from the spec when it comes to formatting numbers with fractions.

We would also be able to remove two Babel plugins from our [testing setup](https://github.com/projectfluent/fluent.js/blob/master/mocha_setup.js): `@babel/plugin-proposal-async-generator-functions` and `@babel/plugin-proposal-object-rest-spread`.

**Comment by stasm** [comment]
We should be careful to not break the consumers of our packages. In particular, `addons-linter` used by `web-ext` still target Node.js 8. @EnTeQuAk are you aware of any plans to move to Node.js 10 now that it's the current active LTS?

**Comment by EnTeQuAk** [comment]
As far as I know `web-ext` isn't planning to do that move anytime soon, so is addons-linter.

cc @rpl though for clarification.

**Comment by stasm** [comment]
My main reason for filing this issue was to be able to drop the outdated polyfill and use the native `PluralRules` implementation available in Node.js 10. Unfortunately it seems like the current implementation of `PluralRules` in Chrome is buggy; @zbraniecki file https://bugs.chromium.org/p/v8/issues/detail?id=8866 about it. So we might want to continue using the polyfill for the time being. I filed https://github.com/eemeli/intl-pluralrules/issues/2 to ask if the polyfill could be updated to match the spec wrt. `minimumFractionDigits`.

**Comment by stasm** [comment]
@EnTeQuAk Thanks, that's good to know. We might want to stick to Node.js 8 for now then.

**Comment by stasm** [comment]
It looks like `addons-linter` and `web-ext` both require Node.js 10 now:
- https://github.com/mozilla/addons-linter/pull/2912
- https://github.com/mozilla/web-ext/pull/1731

According to https://nodejs.org/en/about/releases/ Node.js 8 will be EOL-ed on 31st of December, 2019, which would make January a good time to drop it from Fluent as well.
