### ISSUE TITLE
Document/allow attribute access from a FluentBundle

### ISSUE THREAD

**Issue by eemeli** [projectfluent/fluent.js#358]
See also #208, #282

At the moment, the internal structure of a Message is not public:
https://github.com/projectfluent/fluent.js/blob/326b6ee0667fb877ae19f134485c1716de97ec69/fluent/src/bundle.js#L86-L97

Despite this, it's the interface that at least `fluent-dom` and `fluent-react` use to access message attributes. This makes things difficult for external developers, as `fluent` currently does not provide any other means of accessing them. Is the plan to solve this to wait for #322 to land?

**Comment by stasm** [comment]
Yeah, we should definitely stop doing this in the bindings packages. And you're right: #322 intends to rectify the situation. I didn't have time to work on it before the Syntax 1.0 release, but it's now a top priority for me. Do you think it's the right fix?

**Comment by eemeli** [comment]
Yeah, I at least like the new `compound()` and `format()`, and dropping `getMessage()`. I'll add a comment or two to the PR with a couple of more specific concerns.

**Comment by stasm** [comment]
@eemeli Would you consider this fixed by the `formatPattern` API?

**Comment by eemeli** [comment]
Yes! 🎉
