### ISSUE TITLE
Compile time parsing

### ISSUE THREAD

**Issue by danilobuerger** [projectfluent/fluent.js#359]
Is it possible (or is it planned) to be able to generate the AST from FTL at compile time (for example with a babel macro) to not incur the overhead of having to parse the FTL at runtime?

**Comment by Pike** [comment]
That very conversation is happening in https://discourse.mozilla.org/t/transpiling-fluent-resources-into-javascript-modules/38521 right now.

Note, the overhead isn't bad enough to block us using it in Firefox directly, so you might not want to wait for that.

As that work is happening elsewhere right now, I'll close this issue, too.
