### ISSUE TITLE
ftl template literal tag removes blank lines inside multiline text

### ISSUE THREAD

**Issue by danilobuerger** [projectfluent/fluent.js#362]
Setup bundle like:
```
const test = new FluentBundle("de-DE");
test.addMessages(ftl`
    blank-lines =

        The blank line above this line is ignored.
        This is a second line of the value.

        The blank line above this line is preserved.
`);
```
Calling `test.getMessage("blank-lines")` will return:
```
[
  "The blank line above this line is ignored.",
  "↵",
  "This is a second line of the value.",
  "↵",
  "The blank line above this line is preserved."
]
```
Without `ftl` and dedenting manually it will return:
```
[
  "The blank line above this line is ignored.",
  "↵",
  "This is a second line of the value.",
  "↵↵",
  "The blank line above this line is preserved."
]
```
Notice that the second time it returns two newlines at index 3: `"↵↵"`

**Comment by stasm** [comment]
Hmm, looking at the comment in https://github.com/projectfluent/fluent.js/blob/5593ceb976a594eee4d8420c3ba32eecee7ac878/fluent/src/util.js#L13, I think this was the intended behavior. I admit that I'm not sure why, though :) Perhaps it was an easy way to strip leading and trailing blank lines.

I think it would make more sense to keep all blank lines, including the leading and trailing ones, instead. The parser can handle them fine anyways. And for testing edge-cases involving leading and trailing blank lines, the `ftl` helper is probably not a best choice, anyways.

**Comment by danilobuerger** [comment]
I saw that comment too, and wondered if it was really intended to remove any blank lines or if blank lines inside multiline text was just not considered. As you pointed out, it would just work as well when blank lines are kept. Which would probably be a good choice to not confuse developers new to fluent.

**Comment by Pike** [comment]
Reading https://github.com/projectfluent/fluent.js/commit/ea9618c00ac8b6b94fbf882f1ac93b3704ea5cc3, the blank lines are skipped so that `Math.min` only finds indented lines.

Looking at the last test, it's purpose was to strip whitespace between messages much more than whitespace inside a multiline string.

Proper bug, though, I think.
