### ISSUE TITLE
Emit errors on FluentBundle instances

### ISSUE THREAD

**Issue by stasm** [projectfluent/fluent.js#364]
Rather than passing an `errors` array to `format`, we could emit errors on the `FluentBundle` instance.

**Comment by Pike** [comment]
That makes FluentBundle not reentrant, though? Probably not much of a problem in JavaScript, but as a general runtime API design, I don't think that's a good idea.

**Comment by stasm** [comment]
This is only intended for the JS implementation, yes :)

**Comment by Pike** [comment]
TBH, as long as we only have "one example implementation" to show how to do runtime, I'd recommend to not create APIs that are bad ideas in other languages.

**Comment by stasm** [comment]
We have three, and we'll have a reference one soon, too. I strongly feel that we should design the JS API to be the best in class for JS apps.

**Comment by stasm** [comment]
Can you expand a bit on what you mean by reentrant here? Do you use it as a proxy for _thread-safe_?

**Comment by Pike** [comment]
Not a proxy for, but a condition for thread-safety. https://en.wikipedia.org/wiki/Reentrancy_(computing)

**Comment by eemeli** [comment]
@stasm, could you clarify what you mean by "emit errors on the `FluentBundle` instance"? Would that mean throwing errors from e.g. `bundle.format()`, or having something like a `bundle.onError()` method to register a callback for error reporting?

**Comment by stasm** [comment]
Sorry, I should have been more specific. I meant the latter: `bundle.onerror` or `bundle.addEventListener("error")`.

**Comment by Pike** [comment]
I just realized that this ties in to a pet peeve of mine, and that's runtime error fallback.

I think that not doing fallback on runtime errors is a bug. It's an OK shortcut to get gecko off the ground, but I don't think it's the right design choice.

Moving errors to an API "someone can know" makes it much more cumbersome to implement runtime-error-fallback based on `FluentBundle`.

**Comment by stasm** [comment]
While I don't agree with the premise that we should fall back on runtime errors, I see how switching to the emitter pattern would make that harder. I see `FluentBundle` as a low-level API which should allow many different use-cases and fallback strategies. Let's keep a way to easily query the errors on a per-`format()` basis. Currently this is done by passing the `errors` array as the last argument to `format`. I wonder what the performance impact of returning an array of errors in a `{value, errors}` tuple would be. Do you think that's something worth testing?

I'm not closing this issue yet because I also wonder if it would still make sense to emit errors on the bundle, independent of reporting them on a per-call basis. Would this be helpful for development and debugging, where you'd just attach an event listener to the bundle? For example, in `fluent-react`, the developer has access to bundles which they pass to `<LocalizationProvider>`, but they don't have access to the code calling format for individual messages.

**Comment by Pike** [comment]
We pass in the errors array to avoid having to allocate it for each call. We did that in 2513f002e9d95e59e0e8df8f8cc05f9dd6d8a2d1, [bug 1301198](https://bugzilla.mozilla.org/show_bug.cgi?id=1301198).

**Comment by stasm** [comment]
Yeah, I remember. That was almost 3 years ago, however; the performance impact might be different today :)

**Comment by eemeli** [comment]
Would it not make sense to presume that errors are _exceptional_, and in a low-level API handle them in a JavaScript-appropriate way by throwing them? If that error includes a suggested fallback message, it allows any sort of API to be built on it, such as a higher-level error listener. Sure, this way doesn't allow for more than one error to be returned/thrown at a time, but if the functions only do one thing (e.g. `addResource`, `getMessage`, `formatAttribute`), are there really cases when more than one error would be expected?

Returning a tuple with an error, pushing errors into a prepared errors array and emitting errors to a listener all sound like they're rather opinionated and somewhat non-JavaScriptish ways of dealing with errors.

Or is there a clear and measured benefit from avoiding `throw` at any level of the API?

**Comment by stasm** [comment]
> […] are there really cases when more than one error would be expected?

I think this is the key question here. In the current design of the resolver, it's completely possible that formatting a pattern results in more than one error:

- In `addResource`, we don't want to stop adding messages if a single message causes an error (e.g. it's a duplicate of another one).
- In `formatPattern`, `foo = {$one} and {$two}` can have two errors if neither `$one` nor `$two` are passed as arguments.

The fact that `formatPattern` always returns a string, even if it's a best-effort attempt to resolve as much as it could, is an important part of Fluent's design. Buggy translations must not break the app.

> Or is there a clear and measured benefit from avoiding throw at any level of the API?

I just finished running some tests and indeed, I'm not seeing any impact on our `tools/perf` benchmarks. I've also tried to write a [microbenchmark](https://jsbench.me/vtjy8fsdln/1) which looks similarly promising. I'll need to confirm this still, but I think it means that we should be much more open to throwing errors and catching them in our code.

That said, as far as the public API is concerned, I think we should really consider the design goal of always returning a best-effort string from `formatPattern`. #390 suggested that throwing only happen when the `errors` argument is not present, which could be a good middle ground here.

**Comment by stasm** [comment]
The original issue here was about _emitting_ errors on bundle instance. There were a number of arguments against it, and the discussion evolved into a general discussion about error reporting. Thanks, everyone, for you input. I just merged #396 into the release branch for the next version of `@fluent/bundle`.

The change keeps the current error reporting behavior but makes it _opt-in_: by passing an `errors` array as the third argument to `formatPattern`, consumers of the API can collect more than one error from the operation, and can also rely on `formatPattern` always returning a string.

By default, OTOH, when the third argument is omitted, the first encountered error is thrown from `formatPattern`, as it was suggested by @eemeli.

I think we may close this issue now. Thanks again!
