### ISSUE TITLE
Print expression syntax when references fail

### ISSUE THREAD

**Issue by stasm** [projectfluent/fluent.js#367]
Right now, when a reference fails to resolve, the resolver falls back to the name of the broken variable or message:

    ⁨$username⁩ ⁨added ⁨$photocount⁩ new photos⁩ to ⁨their stream⁩.

I'd like to add braces to this output to make it clearer that it comes from a broken syntax:
```
{$username⁩} ⁨added ⁨{$photocount⁩} new photos⁩ to ⁨their stream⁩.
```

**Comment by eemeli** [comment]
Is there a reason why this error-handling behaviour is not being considered as a part of the spec itself, but rather in an implementation? It seems like a problem that isn't really JavaScript-specific.

**Comment by stasm** [comment]
It should totally be spec. I'll be working on the formatting spec and a reference implementation in May and June. Since I've taken a deep dive into the internals of the resolver for #365, I filed this issue here to not forget about it. It's easy to enough to fix it now, and I think it's something we'd want to formalize in the spec anyways.
