### ISSUE TITLE
[Question] Are comments loaded?

### ISSUE THREAD

**Issue by vzakharov** [projectfluent/fluent.js#373]
For my app’s purposes, I need to be able to read not only strings but also comments from an FTL file. Is this possible with this implementation?

**Comment by Pike** [comment]
I'm sorry, but that's not planned. The runtime parser is heavily optimized for performance, so even adding a switch would probably regress performance. And the tooling parser in `fluent-syntax` isn't designed to create data structures that the resolver can deal with.

What are you trying to achieve?

**Comment by vzakharov** [comment]
Well, one thing I’m missing in PF currently is the lack of context (screenshots, descriptions of fields’ intentions, etc.). I routinely work with translators on Smartcat (you might have heard of it), and there’s a field for comments. I was thinking of creating a FTL uploader for Smartcat (because it doesn’t natively support the format yet and won’t in near future) that would automatically add comments to respective segments for translators’ attention.

**Comment by vzakharov** [comment]
On a side note, why did you decide to base FTL on a totally new format and not, say, YAML? Parsing it would be much easier in a lot of environments, while you could still keep your syntax “flavors” with everything that comes within each string (selectors, etc.)

**Comment by Pike** [comment]
OK, for what you're trying to do, you want to look at `fluent-syntax`, not `fluent-bundle`. `fuent-syntax` creates an AST with all the metadata down to source-code positions that you might need. Keep us posted on how things are going with Smartcat? You might also be interested in our experiences that we blogged about in https://blog.mozilla.org/l10n/2019/04/11/implementing-fluent-in-a-localization-tool/.

Re syntax, we looked at data formats, and you end up parsing data into a native format, or parsing strings in the data format. And YAML in particular is such a beast of a spec, that you'd not only had to maintain a spec of the subset of YAML you require/support, but then also the data mapping. TOML has less features, but still has the problem that you create something that's either really complicated data representation, or something you need to parse twice. And tech and learn twice.

**Comment by eemeli** [comment]
From [experience](https://eemeli.org/yaml/), YAML can be challenging for localizable messages in particular due to its handling of special characters like `{` and `[`, which means that e.g. `foo {bar}` does not need to be quoted to pass as a string value, while `{foo} bar` does need quotes. Especially when you then add in references to messages and terms, I at least completely agree why it makes sense to define a new data format.

And yeah, `fluent-syntax` is probably exactly the tool that you're looking for.

**Comment by stasm** [comment]
> And yeah, fluent-syntax is probably exactly the tool that you're looking for.

Agreed. Closing.
