### ISSUE TITLE
<Localized /> fallback case throws react error if no children are provided

### ISSUE THREAD

**Issue by flut1** [projectfluent/fluent.js#377]
If you use `<Localized />` and it has to revert to the fallback (such as when the `id` was not found in the bundles), `undefined` is returned from the component. This causes a somewhat unhelpful error message:

> Uncaught Invariant Violation: Localized(...): Nothing was returned from render. This usually means a return statement is missing. Or, to render nothing, return null.

**Comment by flut1** [comment]
If you want, I can create a PR that defaults the child element to `null` :

https://github.com/flut1/fluent.js/commit/6adc54b59ca488a8da882b96376ee3dd93347347

But maybe you'd rather add a console warning, or throw an error with a more descriptive message. What do you think?

**Comment by stasm** [comment]
Thanks for filing this issue. Defaulting to `null` sounds good to me. Do you think it would also make sense to use `propTypes` to declare the single child as required?

**Comment by flut1** [comment]
For my current project it's easier to have the fallback locale strings defined in .ftl files, because we would like to display all our fallback copy in a separate CMS. If this fallback copy was inside children of `<Localized />`, we would need to [be able to extract them](https://github.com/projectfluent/fluent.js/wiki/React-Bindings-Discussion#future-plans-extraction). So until that feature is available, I think it's a good idea to continue supporting `<Localized />` without children.
