### ISSUE TITLE
fluent-langneg incorrectly only allows 3-letter-long variants

### ISSUE THREAD

**Issue by stasm** [projectfluent/fluent.js#381]
This surfaced as https://github.com/mozilla/voice-web/issues/2076.

The code which builds the `localeRe` only allows 3-letter-long variants in locale tags:
https://github.com/projectfluent/fluent.js/blob/ab37e1807116f777eb485aa2798ceae4cc17e9a0/fluent-langneg/src/locale.js#L8

As per [BCP47](https://tools.ietf.org/html/bcp47#section-2.2.5), alphanumeric variant subtags should be 5 to 8 characters long, instead.

```
variant = 5*8alphanum         ; registered variants
        / (DIGIT 3alphanum)
```
```
In order to distinguish variants from other types of subtags,
registrations MUST meet the following length and content
restrictions:

1.  Variant subtags that begin with a letter (a-z, A-Z) MUST be
    at least five characters long.

2.  Variant subtags that begin with a digit (0-9) MUST be at
    least four characters long.
```

**Comment by stasm** [comment]
I guess the 3-letter restriction came from the tradition of using `ja-JP-mac` in Gecko, which is then [normalized to `ja-JP-macos`](https://searchfox.org/mozilla-central/source/intl/locale/LocaleService.cpp#43-60) by `LocaleService.cpp`.

@zbraniecki Do you think we could enforce 5-8 characters in `fluent-langneg`? Should we special-case 3 characters, or perhaps just `mac`, as well?

**Comment by zbraniecki** [comment]
So, we currently don't even allow for 3 character variants in MozLocale - https://searchfox.org/mozilla-central/source/intl/locale/MozLocale.cpp (we also don't handle 3 alpahum).

My current approach is to not unify around BCP47, but rather around recently released Unicode Language Identifier standard which is a subset of BCP47 - http://unicode.org/reports/tr35/#Identifiers

It treats variants as:

```
  | = (alphanum{5,8} | digit alphanum{3}) ;
```

so yeah, I'd suggest changing that to conform to UTS35.

**Comment by gion-andri** [comment]
Hi @stasm, hi @zbraniecki,
thanks for your investigations on this topic.

I could take care of this good first bug, but I'm actually not quite sure what to do with all the `-mac` variants used throughout the tests. 

If I understood your intentions, 
```
 | = (alphanum{5,8} | digit alphanum{3}) ; 
```
does not support a `-mac` variant any more. Also, `lij-FA-lin` used in some tests does not seem to contain a valid variant using this variant. 

So, are the tests actually testing incorrect data and should be updated with other examples (like `rm-Latn-CH-sursilv`), or should I search for something like 
```
 | = (alphanum{5,8} | digit alphanum{3} | alpha{3}) ; 
```
as variant?

It somehow feels wrong to replace all the `-mac` tests, as you write that `ja-JP-mac` is widely used in Gecko.

**Comment by zbraniecki** [comment]
Please, replace it with "ja-JP-macos" :) that's a correct language identifier.
