### ISSUE TITLE
Mark internal runtime AST fields as such

### ISSUE THREAD

**Issue by stasm** [projectfluent/fluent.js#386]
To make it more clear that the `Pattern` data structure is internal to this implementation, would it make sense to rename the fields of syntax nodes? E.g. `{type: "var", name: "userName"}` could become `{_type: "var", _name: "userName"}` or `{$$type: "var", $$name: "userName"}`.

**Comment by stasm** [comment]
@Pike, @eemeli - Do you have opinions about this?

**Comment by Pike** [comment]
I think there's two APIs here:

The Fluent API exposed to javascript customers, and the runtime syntax tree API exposed to the Fluent resolver implementation.

I think it'd be weird for the resolver to touch things that are all not to be touched ;-)

Yes, there's the part where we can't clearly delineate one API from the other, but I don't think we should make the resolver code weird to read for that.

If we really needed to do so, I'd constrain the rename to `Pattern` itself. Which, interestingly enough, doesn't exist as a concrete type right now?

**Comment by stasm** [comment]
> The Fluent API exposed to javascript customers, and the runtime syntax tree API exposed to the Fluent resolver implementation.

This issue is only about the internals of the runtime syntax tree. In other words, it's about renaming the fields of `expr` here: https://github.com/projectfluent/fluent.js/blob/ae0c97db1a12a4907f53d98ebda4c10074668359/fluent/src/resolver.js#L102-L103

> If we really needed to do so, I'd constrain the rename to Pattern itself. Which, interestingly enough, doesn't exist as a concrete type right now?

Correct, right now it's a union of `string | Array<Expression>` where `Expression` is a union of many different placeable nodes. I'm thinking that it would be nice to define this explicitly by using TypeScript.

**Comment by eemeli** [comment]
I don't think there's a need to obscure the `Pattern` internals, as long as it's clearly stated that they're not a part of the public API, and that they're liable to change between minor releases. If it does turn out that someone wants to use them, then that's probably a good indicator that the bundle API is not sufficient, and should perhaps be amended or extended.

**Comment by stasm** [comment]
Alright, let's wontfix this then. Thanks!
