### ISSUE TITLE
Throw on bundle.formatPattern if errors would be swallowed

### ISSUE THREAD

**Issue by Pike** [projectfluent/fluent.js#390]
`bundle.format` and soon, `bundle.formatPattern` swallow errors if you don't pass in an errors array.

We should throw on errors instead, I think.

**Comment by stasm** [comment]
Do you think we should:

1. throw to complain that `errors` were not passed as an argument, or…
2. change the error reporting mode and throw a special kind of error containing the array of collected errors?

**Comment by Pike** [comment]
... or ...

3. throw the first error
4. throw the last error

I'd not do 1, I didn't think about 2.

**Comment by eemeli** [comment]
I'd vote for option 3. At that point, no matter what the specific error, showing some fallback string like the message key in the UI is probably at least pretty close to the least wrong thing to do, while printing the error in the console. If the library user wants to do something more complicated than that, that's exactly what the `errors` argument is for.
