### ISSUE TITLE
[fluent] Weird bytes injected around variables?

### ISSUE THREAD

**Issue by atomheartother** [projectfluent/fluent.js#391]
Full disclaimer this is my first time using Fluent and it might very well be a dumb mistake but I can't for the life of me figure out what I'm doing wrong. At first It looked to me like Fluent was adding spaces around every variable post-replacement:

```js
import { FluentBundle } from "fluent";

const bundle = new FluentBundle("en");
bundle.addMessages("link = [A simple markdown link]({$href})");

let msg = bundle.getMessage("link");
console.log(bundle.format(msg, { href: "https://test.com" }));
// [A simple markdown link](⁨ https://test.com⁩ )

bundle.addMessages(`
-name = Tom
apostrophe= It's not mine, it's {-name}'s 
`);
msg = bundle.getMessage("apostrophe");
console.log(bundle.format(msg));
// It's not mine, it's  ⁨Tom⁩ 's⁩
```

As I tried to play around with this, I realized Fluent wasn't adding spaces, it was inserting 4 non-printable bytes around my variables, which I suppose are some Unicode symbol? Anyway these most definitely are not in the original string, they are somehow from Fluent. They're also completely breaking everything, obviously.

Here's what 2 of these taken at random look like (after i put them in files since copying them was a pain)
```sh
$ hexdump -C space1.txt
00000000  e2 81 a9 0a                                       |....|
00000004
$ hexdump -C space2.txt
00000000  e2 81 a8 0a                                       |....|
00000004
```

Fluent version: `0.12.0`
Node version: `v11.15.0`

**Comment by flodolo** [comment]
Those are isolation marks, and should not be visible. How are they breaking completely everything?
https://github.com/projectfluent/fluent.js/wiki/Unicode-Isolation

**Comment by atomheartother** [comment]
Oh, well good to know I'm not misusing the library!

Well in particular they appear to be breaking my markdown links, I'm sending the translated message to Discord and it is not recognizing the format `[text](link)` with the isolation marks around the URL.

I suppose the problem might be on Discord's side though so I guess I'll be disabling isolation marks since this doesn't appear to be a bug on your end. Leaving open for a bit in case anyone has something to add, I'll close the issue shortly.
