### ISSUE TITLE
Control error reporting via a LocalizationProvider prop

### ISSUE THREAD

**Issue by stasm** [projectfluent/fluent.js#411]
We should allow users to control exactly how formatting errors are handled in `Localized` and `getString`. We could do it via a `<LocalizationProvider reportError={...}>` prop, which is a function taking an error.

**Comment by akdetrick** [comment]
I have a real world use case for this. It's common to configure production error reporting to ignore anything at warning level or below. This is an example of a function taking an error that would capture the key miss logging at error level:

```js
const reportKeyMiss = (fluentKeyMissWarning) => {
  Dashboard.withScope((scope) => {
    scope.setLevel("error");
    Dashboard.captureException(fluentKeyMissWarning);
  });
}
```

**Comment by digeomel** [comment]
It is unfortunate that this was done only for React. I'm using `ngx-pdf-extended-viewer` with Angular, which in turn wraps pdf.js, which finally is using Fluent and is dumping a lot of console warnings about missing IDs which I don't want to see.
A global, non-framework-specific solution would be nice.
