### ISSUE TITLE
Whitespace before a paren in CallArguments

### ISSUE THREAD

**Issue by SirNickolas** [projectfluent/fluent.js#419]
```
valid = { NUMBER ("123") }
#                ^ Expected token: "}"
```

I suppose that this time I’ve found a [compliant][spec] example that is [rejected][impl] by the parser.

N.B.: `a = { b .c }` is correctly rejected now, but I couldn’t find a syntax test checking for that. I think it would be nice if there was one.

[spec]: https://github.com/projectfluent/fluent/blob/94dae4de9dcdbdb3a524191f6382b7886fb5bf31/spec/fluent.ebnf#L71
[impl]: https://github.com/projectfluent/fluent.js/blob/43124372ec8fc3f34ccf3232d53664415ed1917d/fluent-syntax/src/parser.js#L679

**Comment by Pike** [comment]
Thanks again, this was fixed in #422.
