### ISSUE TITLE
@fluent/dom release needed?

### ISSUE THREAD

**Issue by psimonyi** [projectfluent/fluent.js#420]
Since the release of fluent-bundle 0.14 renamed `FluentBundle.format` to `formatPattern`, fluent-dom 0.5 is incompatible with it (fluent-dom/src/localization.js:messageFromBundle calls the old 0.13 API `bundle.format` in v0.5, and the new 0.14 API `bundle.formatPattern` in current master).

**Comment by zbraniecki** [comment]
yep! that's on me. Taking. Thanks for filing the issue!

**Comment by zbraniecki** [comment]
Fixed in https://github.com/projectfluent/fluent.js/commit/7c52588be67eb75558bf6a9eb46902169d64f21b
