### ISSUE TITLE
Cannot pass variable named `hasOwnProperty`

### ISSUE THREAD

**Issue by SirNickolas** [projectfluent/fluent.js#428]
```ini
test-without-var = OK
test-with-var = {$var}
```

```json
{
    "var": "OK",
    "hasOwnProperty": 0
}
```

The first message correctly formats to `OK`, but the second one produces `{???}`. At least [this][buggy-line] condition should be changed to `Object.prototype.hasOwnProperty.call(scope.args, name)`; there may be other similiar problems somewhere.

_JavaScript is a wonderful language, isn’t it?_

[buggy-line]: https://github.com/projectfluent/fluent.js/blob/eb26c7665/fluent-bundle/src/resolver.js#L118

**Comment by Pike** [comment]
Yeah, that seems to be the only problem, AFAICT. Luckily, things like `__proto__` aren't valid variable names ;-)
