### ISSUE TITLE
Spread in object literals not supported in Edge (any version)

### ISSUE THREAD

**Issue by gucci-on-fleek** [projectfluent/fluent.js#431]
[Spread in object literals](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax#Spread_in_object_literals) is [not currently supported](https://caniuse.com/#feat=mdn-javascript_operators_spread_spread_in_object_literals) in any version of the Microsoft Edge browser. Tested in Edge 18.18362 on Windows 10 1903 and in Edge 15.15254. According to [#133](https://github.com/projectfluent/fluent.js/issues/133#issuecomment-397448108), and [CHANGELOG.md](https://github.com/projectfluent/fluent.js/blob/7c52588be67eb75558bf6a9eb46902169d64f21b/fluent-dom/CHANGELOG.md#fluent-dom-040), Edge ≥ 15 should be supported. The error in the browser console is:
> SCRIPT1028: SCRIPT1028: Expected identifier, string or number

The file that caused the error is [resource.js](https://github.com/projectfluent/fluent.js/blob/89e351b466e9cbc262fbfce5bce379f08e8ae519/fluent-bundle/src/resource.js#L279). The only other instance of a spread in an object is in [reference_test.js](https://github.com/projectfluent/fluent.js/blob/89e351b466e9cbc262fbfce5bce379f08e8ae519/fluent-syntax/test/reference_test.js#L53) which is unlikely to be ever used in the browser. Microsoft Edge is the only major browser to not support a spread operator in an object literal, but [MDN still calls the feature experimental](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax#Browser_compatibility
).

**Comment by Pike** [comment]
Are you using the compat build? Per https://www.npmjs.com/package/@fluent/bundle#compatibility, only the compat builds have the browser support matrix.

**Comment by gucci-on-fleek** [comment]
Yep, switching to `@fluent/bundle/compat` solved the problem. Thank you! 

You might want to clarify the docs a little bit though, since this affects the *current* version of Edge, not just "legacy" browsers. Maybe change [the `npm` description](https://www.npmjs.com/package/@fluent/bundle#compatibility) to something like this
> # Compatibility
> `fluent` requires the following…
> For legacy browsers **and Microsoft Edge**, the compat build has been transpiled using …  

just to clarify that Edge needs special support.

**Comment by kellda** [comment]
Spread in object literals are now supported from Edge 79 on, according to [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax#Browser_compatibility) and [caniuse](https://caniuse.com/#feat=mdn-javascript_operators_spread_spread_in_object_literals).

However, this still makes many sites just show a blank page on Edge up to 18. Since these versions are still quite used, it would be good to turn on compat build be default or at least strongly advise using it.

**Comment by stasm** [comment]
I removed the compat builds in the latest releases of all `@fluent` packages from last week. The code that we now ship is transpiled by TypeScript to ES2018. See in #472 and #479. It was a maintenance burden to support legacy browsers and to ship multiple builds.

It also didn't feel right that we would be making the decision about the support matrix in the compat builds. I believe the decision should instead be made by developers using `fluent.js`. I'd recommend transpiling `node_modules` selectively to replace the `compat` builds.

**Comment by stasm** [comment]
I'm going to close this issue. Please see my comment above for the rationale and for a possible fix if you need to support legacy browsers. Thanks!
