### ISSUE TITLE
[@fluent/bundle on Safari 12] TypeError: Attempted to set a non-object key in a WeakMap

### ISSUE THREAD

**Issue by fernandogmar** [projectfluent/fluent.js#432]
I got the error `TypeError: Attempted to set a non-object key in a WeakMap` when using @fluent/bundle v0.14.0 on Safari 12:

```
let translation = bundle.getMessage(message_name);
const result = bundle.formatPattern(translation.value, options, errors);
```

with this kind of translations:

```
selection = { $count ->
    *[one]     Selected
    [other]     No selected
}
```

It looks related with the keys: 'one', 'other',.... anything that is not a real number/value Because it works fine when using:

```
selection = { $count ->
    *[1]     Selected
    [0]     No selected
}
```

**Comment by stasm** [comment]
The only place where we use `WeakMap` is when we cache `Intl` formatters using the constructor as the key. Those are `Intl.NumberFormat`, `Intl.DateTimeFormat`, and `Intl.PluralRules`. I'm guessing it's the latter which isn't defined in Safari, which results in `Intl.PluralRules` being `undefined`. If this is in fact what's happening, the solution I'd recommend would be to add the `Intl.PluralRules` polyfill: [intl-pluralrules](https://www.npmjs.com/package/intl-pluralrules) to your project. See https://github.com/projectfluent/fluent.js/tree/master/fluent-bundle#compatibility for more details.

**Comment by stasm** [comment]
Closing. Please reopen if importing `intl-pluralrules` didn't help.

**Comment by fernandogmar** [comment]
yes it was, it worked!
