### ISSUE TITLE
Project heavily inspired by Fluent (and potentially compatible)

### ISSUE THREAD

**Issue by brettz9** [projectfluent/fluent.js#442]
No specific action here, but just thought I'd post for any maintainers/watchers who may have interest.

I've completed an initial release of my internationalization library [intl-dom](https://github.com/brettz9/intl-dom) which is heavily inspired by Fluent and which could conceivably be compatible with it, but which aims to allow working directly with JSON as a file format.

I should have no doubt gathered some feedback on whether such needs might already be met, but I figured you were married to the Fluent file format. And I know it has its advantages over JSON in terms of readability, but for development ease, particularly for small projects, rather than having to deal with a non-JSON format or using your parser to parse Fluent into JSON, I felt it easier to work directly with a JSON locale format (though relying on some abstraction so other formats could potentially be used). The syntax is also of course already familiar, and the parsing is less complex.

Anyways, just sharing for what it's worth. I'll close immediately after posting this so as to avoid polluting your tracker, but feel free to comment (or in the `intl-dom` tracker).

If nothing else, you might find the `ListFormat` or `RelativeTimeFormat` support of interest.

Thanks for your extremely well thought out project!

**Comment by stasm** [comment]
Thanks for the heads-up, @brettz9! This looks really interesting, and from a quick read through the README, the docs are great too. I'll definitely take a close look.
