### ISSUE TITLE
langneg has a circular dependency

### ISSUE THREAD

**Issue by cedeber** [projectfluent/fluent.js#459]
Hello, there is a circular dependency between locale.js and subtags.js.
`locale.js` calls [`subtags.js`](https://github.com/projectfluent/fluent.js/blob/d986155507fcb6c160695cfbfc8d368565313b51/fluent-langneg/src/locale.js#L3) which calls back [`locale.js`](https://github.com/projectfluent/fluent.js/blob/d986155507fcb6c160695cfbfc8d368565313b51/fluent-langneg/src/subtags.js#L1)

**Comment by zbraniecki** [comment]
Is that an issue?

**Comment by cedeber** [comment]
No, not technically. I worry more about code quality and performance. In addition, spaghetti code is not known to be fun to understand/maintain. It's simply an information before it becomes big and nobody cares about anymore.

**Comment by zbraniecki** [comment]
I don't think the fact that two modules depend on each others functions makes it a spaghetti code.

@stasm -wdyt?

**Comment by cedeber** [comment]
Nothing strong here of course. As I said, it was simply informative so that maintainers know about it.

**Comment by stasm** [comment]
Thanks for filing, @cedeber. Rollup complains about this every time I build all fluent.js packages :) I agree with your assessment — it's not a serious issue, but it would be nice to fix it to reduce the build system noise. In larger projects a circular dependency may be a symptom of a deeper issue, but in this case, `@fluent/langneg` is so small that I don't think this cycle hurts.

That said, it should be fairly easy to fix it by moving the `getLikelySubtagsMin` logic out of `subtags.js`. Perhaps into a static method on `Locale`? I'll be happy to review a PR :)
