### ISSUE TITLE
fluent-syntax: `.equals` raises error when comparing two valid Fluent messages

### ISSUE THREAD

**Issue by adngdb** [projectfluent/fluent.js#463]
I'm hitting an edge case in [Pontoon](https://github.com/mozilla/pontoon) where I compare two valid Fluent messages, but one has a `value` and the other only has `attributes`. This makes the `.equals` call raise an unhandled exception that breaks my application. 

Here's a test case: 

```js
import { FluentParser } from '@fluent/syntax';

const fluentParser = new FluentParser({ withSpans: false });

const tA = fluentParser.parseEntry('my-entry = salut');
const tB = fluentParser.parseEntry('my-entry = \n    .myattr = hello');

try {
    tA.equals(tB);
} catch (e) {
    console.debug(e);
}
```

This produces:

```
TypeError: "can't convert null to object"
    equals ast.js:13
    scalarsEqual ast.js:68
    equals ast.js:41
    _existingTranslation selectors.js:34
```

Fluent dependencies versions:
```
    "@fluent/bundle": "^0.15.0",
    "@fluent/langneg": "^0.3.0",
    "@fluent/react": "^0.10.0",
    "@fluent/syntax": "^0.15.0",
```

**Comment by Pike** [comment]
I tried to reproduce this on master, and couldn't. Also on a Pontoon docker image, though I had to crack some skulls to actually have `@fluent` installed there at all?

**Comment by stasm** [comment]
I wasn't able to repro either. Might this be related to how Pontoon handles `EditorState` updates, in particular `initialTranslation? It looks like `.equals()` is receiving a null argument, but I'm not sure where it would come from. Are you able to step through this code with a debugger?

**Comment by Pike** [comment]
More comments from the investigation that stas and I did:

If you're calling into `node.equals` with a node, it only calls back into `.equals` from inside `scalarsEqual`, which *should* check if `otherVal` is a `BaseNode`. Which isn't true for `null`.

Maybe this is transpiled funny? I started reading the transpiled code in my docker image, but that didn't look like it either, I found a `function r(t,e,n){return t instanceof i&&e instanceof i?t.equals(e,n):t===e}`, which smells like `scalarsEqual`.

Obviously, if you actually get `tA.equals(null)` to be called, you're crashing. But we don't see how, in particular not with the stack trace.

**Comment by stasm** [comment]
@adngdb Have you been able to figure this out?

**Comment by adngdb** [comment]
I can't reproduce this with version `0.12.0`. Yay! :relaxed:

**Comment by adngdb** [comment]
(Which, now that I think about it, is weird because it should be related to fluent/syntax and not fluent/react, and the syntax library version didn't change… )

**Comment by stasm** [comment]
Thanks for verifying!
