### ISSUE TITLE
Add React Hooks

### ISSUE THREAD

**Issue by macabeus** [projectfluent/fluent.js#467]
`fluent-react` provides a simpler way to use fluent on a React application, but it's laking a built-in function to get messages using react hooks.
Currently is possible to get the messages just using a HOC using `withLocalization` or with `<Localized />`.

It's a similar approach that [`react-i18next`](https://react.i18next.com/latest/usetranslation-hook) already do.

Sometimes is better just to call a function instead of increasing the JSX code wrapping each message with the `<Localized />` component. For example, [here](https://github.com/mozilla/activate.mozilla.community/blob/master/src/components/Header.js#L82-L84):
```jsx
<Localized id="nav-campaigns">
  <span></span>
</Localized>

<!-- would be just... -->
<span>{t('nav-campaigns')}</span>
```

Related: https://github.com/projectfluent/fluent.js/issues/182

**Comment by stasm** [comment]
Thanks for your work on this, @macabeus! I released `@fluent/react` 0.13 last week with your changes: https://github.com/projectfluent/fluent.js/blob/master/fluent-react/CHANGELOG.md#fluentreact-0130-july-2-2020. I also added a note about `useLocalization` on the wiki: https://github.com/projectfluent/fluent.js/wiki/useLocalization
