### ISSUE TITLE
Sometimes @fluent/react is violating the rule of hooks

### ISSUE THREAD

**Issue by macabeus** [projectfluent/fluent.js#473]
The bundle of `@fluent/react` is vendoring React, so it'll violate [the third rule of hooks](https://reactjs.org/warnings/invalid-hook-call-warning.html). We could check that logging the version inside of package and on the application:

![image](https://user-images.githubusercontent.com/9501115/78989192-dc1dba00-7b2a-11ea-9e1b-1276ea14c6c8.png)

We can check that on applications inside of examples folders (after update its code to new `@fluent/react` version). Just for testing, I created a new one importing `@fluent/react`, and I have the same problem, using yarn or npm.

I already checked a lot of the code and the build process, but I really don't know exactly why it happens.
I tried adding the flag `--external react` on rollup, as well as creating a new build process, but it didn't solve the problem.

A workaround was just removing removing `react` on `fluent-react/package.json`. We still can build `@fluent/react` because we have the types, but it don't looks like a good approach.

**Comment by stasm** [comment]
Hmm, this is strange. I know I had similar problems when testing `@fluent/react` locally via `npm link`. However, when I switched to `npm pack` or when using the published versions from npm, I haven't seen any issues anymore.

What do you mean by _The bundle of @fluent/react is vendoring React_? I'm pretty sure we only have `react` as a `peerDependency`; my understanding is that it should use the React instance installed in your project 🤔.

From your screenshot, it looks like this isn't what's happening. Where do you log the first two lines from?

**Comment by macabeus** [comment]
Yeah. I was having this problem when I developing that locally, using on `package.json` `file:my/path`.
But I just noticed now that you updated the examples to use `npm pack` and `file:fluent-react.tgz` (I didn't updated my code yet).  So after I updated repository, now it's working fine. Thanks!

Do you know why the bug was happening on the past approach? It don't make sense for me.

> From your screenshot, it looks like this isn't what's happening. Where do you log the first two lines from?

I added the `console.log` on `fluent-react/src/localized.ts` file:

```diff
diff --git a/fluent-react/src/localized.ts b/fluent-react/src/localized.ts
index 9782cc02..f0d940b4 100644
--- a/fluent-react/src/localized.ts
+++ b/fluent-react/src/localized.ts
@@ -1,4 +1,4 @@
-import {
+import React, {
   Fragment,
   ReactElement,
   ReactNode,
@@ -12,6 +12,8 @@ import voidElementTags from "../vendor/voidElementTags";
 import { FluentContext } from "./context";
 import { FluentArgument } from "@fluent/bundle";
 
+console.log('React version on fluent.js:', React.version)
+
 // Match the opening angle bracket (<) in HTML tags, and HTML entities like
 // &amp;, &#0038;, &#x0026;.
 const reMarkup = /<|&#?\w+;/;
```

**Comment by macabeus** [comment]
I didn't found a built-in way to automatically hot reload the server when changing something on `@fluent/react` codebase, so I wrote this (bad) code to do that:

```
make && npm pack && mv fluent-react-*.tgz example/fluent-react.tgz && rm -rf example/package-lock.json example/node_modules/@fluent/react && cd example && npm i && echo -n "" >> package.json && truncate -s -1 package.json && cd ..
```

I'm removing the old `@fluent/react` package on `example/node_module`, removing `example/package-lock.json` in order to force to reinstall and append-and-removing a line on `package.json` just to force to parcel to re-build.

**Comment by stasm** [comment]
> Do you know why the bug was happening on the past approach? It don't make sense for me.

When using `npm link` or `file:path/to/fluent-react`, the imports inside `@fluent/react`'s code resolve to React in path/to/fluent-react/node_modules/react` rather than React in your project's `node_modules`. Hence two versions of React running next to each other, which violates the rules of hooks.

`npm pack` solves this by essentially emulating `npm publish`. You then `npm install` the tgz, which literally unpacks `@fluent/react`'s source code into your projects `node_modules`. The imports will now resolve to the same React as the rest of the app.
