### ISSUE TITLE
Load language files inside Create React App

### ISSUE THREAD

**Issue by cmnstmntmn** [projectfluent/fluent.js#476]
Hei,

I'm not sure how i could dinamicaly get a list of paths inside a CRA/webpack.
I'm referring to [this line](https://github.com/projectfluent/fluent.js/blob/master/fluent-react/example/src/l10n.tsx#L8) here.

thank you

**Comment by Pike** [comment]
Yeah, I've dug into docs over docs myself, until I ended up trusting the comment, and looking up parcel docs.

https://parceljs.org/module_resolution.html#glob-file-paths is specifying that this is a mapping from local path to upstream path.

Doing discovery of available languages in other packagers is a very different beast, I guess.

**Comment by macabeus** [comment]
@cmnstmntmn You should add on your webpack the [file-loader](https://github.com/webpack-contrib/file-loader) with the following rule:
```
{
  test: /\.ftl$/, // will match all files ending with .ftl
  use: 'file-loader', // our loader
  exclude: /node_modules/, // doesn't matter files inside of node_modules
}
```

So now you could do something like:
```
import fluentFile from './i10n/pt-br.ftl' // fluentFile will be pt-br.ftl's path
```

I don't if you'll need to eject from CRA

**Comment by cmnstmntmn** [comment]
@macabeus that loader it already presend in CRA;
i'm getting the url with `require("./locale/ro/general.ftl")`, my question was about wildcard imports or glob-file-paths as @Pike mentioned.

**Comment by stasm** [comment]
In the example app, I've taken the liberty to use Parcel's glob file paths feature, which @Pike linked to. I don't know Webpack well enough to recommend the best way of achieving the same result. A quick search didn't yield anything promising, either. If Webpack is not able to do it, then I think you'll either need to require/import each Fluent file separately, or try to write a custom loader.

**Comment by stasm** [comment]
@cmnstmntmn Do you think this issue can be closed now?

**Comment by cmnstmntmn** [comment]
@stasm yeap, thanks ;)
