### ISSUE TITLE
Placeables insert undesired spaces around.

### ISSUE THREAD

**Issue by davojan** [projectfluent/fluent.js#484]
I'm using ``@fluent/bundle`` and when translating this id:
```
auth-sms-code = Auth code:-{ $code }-
```
with ``{ code: 1234 }`` (numeric, without any spaces) the result looks like:
```
Auth code:- 1234 -
```
Those spaces might be a bug, they are totally unexpected and limits translators. I din't find anything in docs pointing this as expected behaviour.

**Comment by Pike** [comment]
I've tried this on the playground, and couldn't reproduce.

But you might see invisible characters from our bidi isolation, https://github.com/projectfluent/fluent/wiki/BiDi-in-Fluent.

**Comment by Pike** [comment]
PS: You can switch that off via `useIsolating: false` in https://projectfluent.org/fluent.js/bundle/classes/fluentbundle.html

**Comment by davojan** [comment]
@Pike thanks a lot, it helped! 🙏🏼🙏🏼🙏🏼

I don't really understand what the BiDi thing is, but it seems that most of languages doesn't need that feature and the default value of ``useIsolating`` is misleading.
