### ISSUE TITLE
fluentfmt.js doesn't parse newlines correctly

### ISSUE THREAD

**Issue by 6a68** [projectfluent/fluent.js#50]
`fluentfmt.js` incorrectly absorbs keys into preceding comments under certain circumstances. I'm not quite sure of the exact parsing bug, but here's a test case to experiment with:

test.ftl:
```
// Foo page

fooPageTitle = Foo

// Test page

testPageHelloWorld = Hello, world!
```

Output of `fluentfmt.js test.ftl`:
```
// Foo page

fooPageTitle = Foo
// Test pagetestPageHelloWorld = Hello, world!
```

**Comment by stasm** [comment]
Thanks for filing the issue, @6a68. The fix landed recently in python-fluent ([bug 1382619](https://bugzilla.mozilla.org/show_bug.cgi?id=1382619). I'll port it to fluent.js.
