### ISSUE TITLE
Feature request: allow sharing messages and terms between bundles

### ISSUE THREAD

**Issue by Demivan** [projectfluent/fluent.js#503]
I'm working on Vue.js library for fluent.js and wanted to add functionality to split localization into multiple bundles. But I want to be able to share commonly used messages and terms across bundles. Here is simple implementation of a bundle that has this functionality:
https://github.com/Demivan/fluent-vue/blob/7cdd3932130a76b7b270c1113860fb3a3fc8c30f/packages/fluent-vue/src/extendedFluentBundle.ts
This is pretty mush all of it:
```js
getMessage(id: string): Message | undefined {
  return this._messages.get(id) || this.parent.getMessage(id)
}
```
Problem with it is that child bundle cannot reference parent terms or messages because resolver does not call `getMessage` method but is accessing `_messages` directly:
https://github.com/projectfluent/fluent.js/blob/f41d910dd3bbf13ac057026060a0666426796870/fluent-bundle/src/resolver.ts#L205
Can something like this https://github.com/projectfluent/fluent.js/commit/e07d6f7c17c34dec2f2ced35d3bfaa089df276c3 be added so it is possible to implement this functionality?
Or maybe there is other way of sharing messages and terms?

**Comment by macabeus** [comment]
> Problem with it is that child bundle cannot reference parent terms or messages

I'm sorry, but I can't understand very well the problem that you said here.

I tried the following code:

```js
const resourceCommon = new FluentResource(`
-foo = Foo Term
common = Common Message`)

const resource = new FluentResource(`
test = Test { common } { -foo }`)

const bundle = new FluentBundle('lng')
bundle.addResource(resourceCommon)
bundle.addResource(resource)

const testMessage = bundle.getMessage('test')
const testText = bundle.formatPattern(testMessage.value)
console.log(testText) // Test ⁨Common Message⁩ ⁨Foo Te
```

That is, on the child bundle I can get the terms and messages from the parent.

Do you want to do something different?

**Comment by Demivan** [comment]
I have considered doing it this way. Downside of this approach is that changes to parent bundle are not reflected in child bundles as messages are just copied.
Maybe that's fine, bundles shouldn't really change.

**Comment by Demivan** [comment]
Going to close this. Copying messages and terms works

**Comment by stasm** [comment]
Sorry I didn't comment earlier. I'd prefer to avoid allowing parent-child hierarchies of bundles. While bundles are mono-lingual, two bundles may be in different languages, have different constructor options (e.g. custom `functions` or `useIsolating`), and they cache their own `Intl` formatters too.

Since messages can reference other messages (and terms), `formatPattern` does cycle detection to prevent unresolvable cyclic reference. While the current detection would probably work in a scenario where bundles can have parents, the concept of a messgae reference would also become more complex.

That said, I think it might be a good idea to consider a different lookup model than the current one. Perhaps rather than copying messages into the bundle, we could store references to `FluentResources` and iterate over them in `getMessage`? @Pike Do you have an opinion about this?

**Comment by Demivan** [comment]
By the way, why `Intl` formatters are cached inside a bundle? From what I can see they don't depend on bundle itself, only on its locale. I'm creating a lot of bundles with same locale and cache could be shared between them.

**Comment by Pike** [comment]
My thinking is based on my writings in https://discourse.mozilla.org/t/on-message-and-termreferences/53217 and https://discourse.mozilla.org/t/semantics-of-bundles-fallbacks/63107.

I'd like for us to fix the problems around language fallbacks, and references with fallbacks. The longer I think about possible solutions, the less the current concept of Bundle helps, and the more I see the localization class concept move to the forefront.

Localization would be a cross-language cross-source concept, and language annotations for formatting and selectors would move to entries or patterns.

The questions we had about currency formatting in the case of falling back among English locales also makes me wonder if we should actually use the current bundle locale list for formatting, or the full language fallback list.

**Comment by stasm** [comment]
> By the way, why `Intl` formatters are cached inside a bundle? From what I can see they don't depend on bundle itself, only on its locale. I'm creating a lot of bundles with same locale and cache could be shared between them.

That's #218. We've never had a strong use-case for it and most JS apps we've seen don't create more bundles than just a few.

**Comment by Demivan** [comment]
Global, per locale cache instead of per bundle cache would be really nice to have. Can I create pull request that implements it?

**Comment by zanona** [comment]
I am doing some testing having a template `en` bundle, and a localized one, `zh-CN`
on my template bundle, I have:

```yml
# /locales/en/products.ftl
-product-color--11ae039e = Tangerine
product-3050-20-color = { -product-color--11ae039e }
```

on the localized one
```yml
# locales/zh-CN/products.ftl
-product-color--11ae039e = 柑橘
```

So I'd think that `<Localized id='product-3050-20-color'/>` with locale set to `zh-CN` would return the localized string `柑橘`, but it's in fact returning the original string from the template `Tangerine`.

I am not completely sure this relates to this issue but I'd expect that by just replacing the term on the localized version would be enough to update the message itself? Or perhaps I'm missing something?

The translation was generated from Pontoon, which does not add the affected message which uses the term to the commit.

So in this case, the only way to get this working was repeating myself and re-declaring the message again as below, which could become a bit difficult to maintain. 

```yml
# locales/zh-CN/products.ftl
-product-color--11ae039e = 柑橘
product-3050-20-color = { -product-color--11ae039e }
```
