### ISSUE TITLE
fluent/syntax: A visitor with visitMessage block others visitors calls

### ISSUE THREAD

**Issue by macabeus** [projectfluent/fluent.js#509]
While I was developing [this visitor](https://github.com/macabeus/vscode-fluent/blob/5b13cbf8f925e9acc1845b29f8c2bf3da7cedf73/src/global-state/parser.ts#L11), I noticed that when I try to add a `visitMessageReference` or a `visitVariableReference`, these functions are never called, even when my `.flt` has references.

But I noticed that if I remove the function `visitMessage`, the `visitMessageReference` and `visitVariableReference` are called.

I think that it isn't expected and it's a bug.

I wrote a workaround using [another visitor](https://github.com/macabeus/vscode-fluent/blob/b26620ab756b143f5eeba7e90ecad70db48357f1/src/global-state/parser.ts#L79), but I would like to write just one, in order to have a faster and simpler code.

**Comment by Pike** [comment]
Nice to see you working on more syntax features :-)

This is a feature of the visitor pattern, https://www.projectfluent.org/fluent.js/syntax/classes/visitor.html

>  Then, to descend into children call genericVisit.

We have a usage page for python, https://www.projectfluent.org/python-fluent/fluent.syntax/stable/usage.html#analysis-visitor.

**Comment by macabeus** [comment]
@Pike I didn't notice that the solution is just calling a method. Thank you =P
