### ISSUE TITLE
err  Repo npm:@fluent/bundle not found!

### ISSUE THREAD

**Issue by fernandogmar** [projectfluent/fluent.js#511]
trying to install `@fluent/bundle` using `npm install @fluent/bundle` gave me next error:

```
err  Repo npm:@fluent/bundle not found!
```

**Comment by Demivan** [comment]
There is issue with npm right now: https://status.npmjs.org/incidents/cksjqc1w11v5

**Comment by fernandogmar** [comment]
Thanks it is back again ;)
