### ISSUE TITLE
In fluent-react, when an id is not found, it should report an error

### ISSUE THREAD

**Issue by gregtatum** [projectfluent/fluent.js#519]
https://github.com/projectfluent/fluent.js/blob/72f59706128e648a4aaff5ca294bdc39a7d366fc/fluent-react/src/localized.ts#L63-L68

I'm currently using fluent-react and my UI was not translating correctly with no errors reported. The issue turned out to be missing `id`s in my bundle.

For example:

<img width="736" alt="image" src="https://user-images.githubusercontent.com/1588648/101388802-10967100-3886-11eb-8a86-2a790c88708b.png">

**Comment by gregtatum** [comment]
I'll work on this.

**Comment by julienw** [comment]
May I suggest to render the l10n-id when the child is null (in addition to report an error to the console maybe)? I believe this is what the "main" fluent library is doing, it would be nice that the react binding follows the same behavior.
