### ISSUE TITLE
@fluent/langneg - README examples swapped?

### ISSUE THREAD

**Issue by davidrios** [projectfluent/fluent.js#547]
Hi. The readme for langneg gives the following examples for the available strategies:

## filtering
requested: ['de-DE', 'fr-FR'] available: ['it', 'de', 'en-US', 'fr-CA', 'de-DE', 'fr', 'de-AU']
supported: ['de-DE', 'fr']

## matching
requested: ['de-DE', 'fr-FR'] available: ['it', 'de', 'en-US', 'fr-CA', 'de-DE', 'fr', 'de-AU']
supported: ['de-DE', 'de', 'fr', 'fr-CA']

But when I run it, this is what I get:

![image](https://user-images.githubusercontent.com/1418372/114294017-83506c80-9a71-11eb-9e4b-9f029c993c16.png)

Seems like the examples are swapped. Is that the case?

**Comment by Pike** [comment]
Yes, and even more so, the complete docs were swapped, comparing to https://projectfluent.org/fluent.js/langneg/modules.html#negotiatelanguages

**Comment by Pike** [comment]
Landed, released 0.5.2 to update docs on https://www.npmjs.com/package/@fluent/langneg, pushed updated docs to gh-pages.
