### ISSUE TITLE
getIndexOfType is broken

### ISSUE THREAD

**Issue by stasm** [projectfluent/fluent.js#56]
@zbraniecki noticed something weird about this code: https://github.com/projectfluent/fluent.js/blob/aea7315912cba4f7e4e1e632a0e6357235d99487/fluent-dom/src/overlay.js#L257

I looked into it. The code is broken and possibly never worked in the first place. The only reason why it doesn't go into an infinite loop is that a few lines before there's this:

    translationElement.removeChild(childElement);

Which means that by the time we get into `getIndexOfType`, `element` is always the first sibling.

**Comment by zbraniecki** [comment]
Thanks. I'd like to request high priority on it since it's part of the code we're in the process of landing in Gecko.

**Comment by stasm** [comment]
Let's remove the feature of being able to reorder elements of the same type. for the time being. DOM overlays are quite powerful even without it and already make localizers' experience much better than the status quo.

I don't mean to say that I'd like to remove this feature permanently. I plan to revisit the topic of DOM localization related to fluent-react, so I'll have some time in Q3 to work on this. That said, I would prefer the code to be more dumb and to do less rather than more things.

@zbraniecki, I can prepare a PR on Monday if you agree with this course of action.

**Comment by zbraniecki** [comment]
Yeah, sgtm!
