### ISSUE TITLE
Last version with type:commonjs ?

### ISSUE THREAD

**Issue by DamienA24** [projectfluent/fluent.js#561]
Hello,

I loaded last version (0.16.1) and I always have in package.json "type:commonjs", is that normal ?

I tried with npm install or yarn add, same issue...

Thank you

**Comment by gregtatum** [comment]
This should be fixed in #556, and we're planning on doing a release this week. After we do the release, please comment to re-open if it's still not fixed.

**Comment by danburzo** [comment]
Hi @gregtatum, would there be time for the release with the #556 fix? It's currently a blocking issue for upgrading to Webpack 5. (As a stopgap solution I can publish a fork, but I'd rather avoid it.)

**Comment by gregtatum** [comment]
@eemeli Do you want to try doing a first deploy?

**Comment by eemeli** [comment]
Sure! I'll see about packaging & publishing a release on Monday or Tuesday.
