### ISSUE TITLE
[fluent-syntax] Calling `clone()` on a node should return a value with node's type, not `BaseNode`

### ISSUE THREAD

**Issue by eemeli** [projectfluent/fluent.js#589]
The correct TS type here would be `this`:

https://github.com/projectfluent/fluent.js/blob/a68c20eaea45ae8f948570e6b2ac13f2f0306b5b/fluent-syntax/src/ast.ts#L50

**Comment by AleksandrSl** [comment]
The issue seems to be resolved, so it can be closed 😀
