### ISSUE TITLE
Remove fetchSync from fluent-web

### ISSUE THREAD

**Issue by stasm** [projectfluent/fluent.js#59]
Sync XHR is deprecated. We shouldn't use it to download localization resources. If FOUC is a concern, let's research other avenues for improving the perf. For instance:

  - the `display: none` trick,
  - `rel=prefetch` and `rel=preload`
  - server-side language-negotiation
  - build-time optimizations for above-the-fold content
  - others?

**Comment by zbraniecki** [comment]
I fixed it in https://github.com/projectfluent/fluent.js/commit/50d553796139abf2f07ae6ac3d04cf836c79edb0
