### ISSUE TITLE
Ability to compile bundle into a smaller resource

### ISSUE THREAD

**Issue by willfarrell** [projectfluent/fluent.js#592]
Similar to how [`ajv`](https://ajv.js.org/packages/ajv-cli.html) allows compiling a JSON Schema into a validation function. The ability to compile a `ftl` file into am esm with tree shaking support.

The interface I'm imaging could go something like ...

Source en.ftl files:
```ftl
-brand-name = Foo 3000
welcome = Welcome, {$name}, to {-brand-name}!
bigWelcome = Big welcome to {$name} on joining the  {-brand-name} team.
```

Compiles to something like en.ftl.js
```js
// Note any preprocessing that can be done, has been to ensure the least amount of code is needed to be shipped.
export const welcome = (params) => transformParams(`Welcome, {$name}, to Foo 3000!`, params)
export const bigWelcome = (params) => transformParams(`Big welcome to {$name} on joining the Foo 3000 team.`, params)

const transformParams = (msg, params) => ...
```

It could then be used in Sveltekit like:
```svelte
<script>
export let locale = 'en'
export let name = 'Everyone'

const {welcome} = await import(`./${locale}.ftl.js')
<script>

<h1>{welcome({name})}</h1>
```

This would allow the same files to be imported where ever it's needed but only include the messages needed. This would greatly reduce the bundle size on large projects single translation files that take advantage of progressive enhancement / hydration strategies.

**Comment by eemeli** [comment]
A while ago I built something like this, [fluent-compiler](https://github.com/eemeli/fluent-compiler), but have not updated it since; it's mostly based on the same thinking that's behind the [messageformat](https://github.com/messageformat/messageformat) project.

If you're interested in building something like what you suggest, that's probably a pretty good starting point?

**Comment by willfarrell** [comment]
Thanks for the resources, I'll check them out. I'll put it on my side project list. Will keep you posted, but might take a while for me to get to it. Thanks again.

**Comment by willfarrell** [comment]
Just ran across this (https://github.com/cibernox/svelte-intl-precompile). Similar implementation for ICU.

**Comment by willfarrell** [comment]
I finally found some time to work on this and have build https://github.com/willfarrell/fluent-transpiler. Thanks for fluent-compiler, it was helpful in verify my implementation was feature complete.

You can find a sample output in the test folder if you're curious: https://github.com/willfarrell/fluent-transpiler/blob/main/test/files/index.mjs
