### ISSUE TITLE
Tests are ignoring junk annotations

### ISSUE THREAD

**Issue by Demivan** [projectfluent/fluent.js#594]
I'm writing a C# parser and want to make sure it is 100% correct.

https://github.com/projectfluent/fluent.js/blob/5d3fd8f3e4418f9c819e6364ad1ac9bbfe056a2a/fluent-syntax/test/reference_test.js#L48-L53

This says that parser is not producing annotations, but it is. Or is this talking about some different "reference" parser?

**Comment by eemeli** [comment]
The "reference parser" this refers to is the one included in the [projectfluent/fluent](https://github.com/projectfluent/fluent) repository, rather than the parsers hosted in this repository and published on npm as `@fluent/bundle` and `@fluent/syntax`.

**Comment by Demivan** [comment]
Thanks. Will take a look into that parser too then.
