### ISSUE TITLE
[fluent-langneg] breaking changes in module exports from 0.0.2 to 0.0.3

### ISSUE THREAD

**Issue by 6a68** [projectfluent/fluent.js#61]
In 0.0.2, `require("fluent-langneg")` exported the single function `negotiateLanguages`.

In 0.0.3, the export is an object of the form `{ default, acceptedLanguages }`, where `negotiateLanguages` is assigned to `default`.

This breaks existing clients that loaded the main export node-style:
```js
const { negotiateLanguages } = require('fluent-langneg')
```

Same issue occurs with the compat builds. Not a huge deal, but would have been nice to see a larger version number bump to signify API changes. Would be great to see the new API added to the README, too :+1:

**Comment by stasm** [comment]
This is related to #39. @zbraniecki, are you okay with not using the default export at all here?

**Comment by zbraniecki** [comment]
Yeah, I think so. No plans for any changes.

**Comment by stasm** [comment]
I published `fluent-langneg` [0.1.0](https://github.com/projectfluent/fluent.js/releases/tag/fluent-langneg%400.1.0) which exports `negotiateLanguages` as a named export now.

When upgrading from 0.0.2, please change:

    import negotiateLanguages from 'fluent-langneg';

to:

    import { negotiateLanguages } from 'fluent-langneg';
