### ISSUE TITLE
Lines with unusual characters at start inside of multiline text do not get properly recognized.

### ISSUE THREAD

**Issue by elenakrittik** [projectfluent/fluent.js#620]
```ftl
registration_title = Registration
registration_description_1 = You don't have a playable character yet. Let's create one!
    Answer the questions that come up.

    **What's your favorite playstyle?**

registration_choose_an_answer = Choose an answer
```
![image](https://github.com/macabeus/vscode-fluent/assets/77104725/b5d0dc49-b391-4184-99bd-92399ff139ee)

The problem arises from the usage of `*` at the start of a non-first line of a multiline string. If i place a `*` at the beginning of `Answer ...` the error moves there, and if i remove all `*` from the start the error disappears.

Reproducible on [Fluent Playground](https://projectfluent.org/play/?id=74f1ef82da0a06bf7493a58d8cad53ae)

**Comment by eemeli** [comment]
This isn't a bug; the `*` is not a valid [`indented_char`](https://github.com/projectfluent/fluent/blob/feffc720fa5d5621a703f42731d709e216fc6730/spec/fluent.ebnf#L110), which is the rule used for first characters on pattern lines after the first.

**Comment by elenakrittik** [comment]
If so, what would be the correct way to include `*`s at the start of a multiline string? Put them as `{ "*" }`? And also, python-fluent works with the example l10n just fine. Is such disrepancy in behavior considered an implementation bug?

**Comment by eemeli** [comment]
Yes, that's the right way to quote the `*`. And it sounds like you're describing a bug in python-fluent.

**Comment by elenakrittik** [comment]
Thanks, sorry for disturbing.
