### ISSUE TITLE
Uncaught TypeError: Failed to resolve module specifier "cached-iterable"

### ISSUE THREAD

**Issue by dineshpithiya-virtusa** [projectfluent/fluent.js#629]
I am getting this error from **node_modules\@fluent\dom\esm\localization.js** 
I see cached-iterable dependency also already installed in root node_modules. But still it's return same error.
My folder structure look like below
```
- node_modules
 - @fluent
 - @mapbox
 - cached-iterable
 - pdfjs-dist  
- src
- web
```
Root folder structure image

**Comment by eemeli** [comment]
This is probably not a Fluent bug, but something weird in your local environment. Can you provide a minimal reproduction of the error, as otherwise it's pretty much impossible to debug?

**Comment by dineshpithiya** [comment]
Let me share code sample repository. you can install npm and see error as like I shared and If I fixed inside node_modules@fluent\dom\esm\localization.js then only it's working.
[testp.zip](https://github.com/projectfluent/fluent.js/files/14819546/testp.zip)

**Comment by dineshpithiya** [comment]
unzip sample-pdf.zip folder
go inside folder and npm install
-   sample-pdf
    -   package.json
    -   src
    -   web
        -   viewer.html

-   To run file need any server.
    -   I am using live-server
    -   To install this 
        ```
        npm install -g live-server
        ```
    -   Go to the sample-pdf root folder using terminal and run below command
        ```
        live-server
        ```
    -   now go inside the web folder and click on viewer.html page
    -   open console and you will see error as like above.
[sample-pdf.zip](https://github.com/projectfluent/fluent.js/files/14819596/sample-pdf.zip)

**Comment by eemeli** [comment]
That is not a minimal reproduction. That's 135k lines of code.

I'm not going to run that on my machine, but by inspection you've at least commented out your import map.

Closing, as this really isn't a Fluent issue.
