### ISSUE TITLE
fluent-syntax: Allow Placeables inside other Placeables

### ISSUE THREAD

**Issue by stasm** [projectfluent/fluent.js#66]
This should be possible:

    key1 = {{ foo }}
    key2 = {     { foo }     }
    key3 = 
        {
            { foo }
        }

**Comment by zbraniecki** [comment]
What's the purpose?

**Comment by stasm** [comment]
Grouping: https://github.com/projectfluent/fluent/pull/21

**Comment by zbraniecki** [comment]
Is that an artifact of the EBNF grammar or do you expect that anyone will actually have a reason to try to write FTL using this?

**Comment by stasm** [comment]
https://github.com/projectfluent/fluent/issues/3 has the use-case: list-typed selectors.

**Comment by stasm** [comment]
This was fixed in #287.
