### ISSUE TITLE
fluent-syntax: Add syntax for plain text interpolation

### ISSUE THREAD

**Issue by mortyccp** [projectfluent/fluent.js#74]
Currently we have [Message References](http://projectfluent.io/fluent/guide/references.html). 
```
brandName = Loki
installing = Installing { brandName }.

menu-save = Save
help-menu-save = Click "{ menu-save }" to save the file.
```
This indicate the translator to not translate the what inside the `{ }`.

I suggest we can add another syntax to make the contents to be translated too.
For example
```
alert_message = Click #{ here } for more detail.
```

This is useful because we can keep the sentence to be translated all together. And if we provide AST form of the translated result, we provide the renderer ability to further enhance the appearance or behaviour of the word `here`.

**Comment by zbraniecki** [comment]
How is that different from:

```
alert_message = Click \{ here } for more detail.
```

?

**Comment by stasm** [comment]
It sounds like @mortyccp would like the AST to still reflect the fact that `here` is in a Placeable. If so, then escaping won't cut it. I might suggest the following solution:

    alert_message = Click { "here" } for more detail.

**Comment by mortyccp** [comment]
@stasm Ya it is exactly what I want.

**Comment by mortyccp** [comment]
One more thing I would like to ask is how this Placeable will be represented in the AST? Does it have identifier for which Placeable it is?

**Comment by stasm** [comment]
No, there won't be an identifier, just a `Placeable` with a `StringExpression` in it. Also note that there has been a recent change to the AST of Placables: in _fluent-syntax_ 0.5.0 the `StringExpression` will be a sibling of other elements of the `Pattern`. In #64 we changed this: there's now an intermediate `Placeable` node. I haven't yet released a new version of _fluent-syntax_ with this change.

**Comment by stasm** [comment]
`fluent-syntax` 0.6 has been published and it includes the addition of `AST.Placeable`. I'm going to close this issue as it looks like https://github.com/projectfluent/fluent.js/issues/74#issuecomment-329750016 has a viable solution to the original problem.
