### ISSUE TITLE
Rename fluent-langneg to fluent-locale

### ISSUE THREAD

**Issue by zbraniecki** [projectfluent/fluent.js#75]
I've started working on a Rust port of `fluent-langneg` and started thinking more about the role of this package in the Fluent ecosystem.

While all it does on the surface at the moment is negotiate languages, the package provides a more complete functionality including:

* Opinionated definition of locale id, locale range, extension keys etc.
* Ability to parse and serialize the locale id
* Ability to handle language tags
* Opinionated logic of negotiating locales and languages

This functionality is necessary for Fluent to work, and it fits into CLDR/ICU logic, but it goes beyond just negotiation.

For example, in ECMA402 we're currently working on `Intl.Locale` API which will be *very* similar to what we did in fluent-langneg for the Locale class (maybe because I'm the author of the proposal, who knows).

I believe that even raw functionality like parsing/serializing and operating on locale tags is useful beyond just negotiation. In the current `fluent-langneg` it can be easily achieved by exposing the Locale class, and soon we'll be able to possibly just replace it with calls to `Intl.Locale` (I'm not 100% sure if we will, because `Intl.Locale` may not support ranges in the first version).

For `fluent-langneg-rs` it would make sense to expose more than just language negotiation, so I believe that `fluent-locale-rs` is a better name for the package. Same for the python version.

I know it's a hassle to change the name, but I think it makes sense to do it in this case.

**Comment by zbraniecki** [comment]
@stasm - thoughts?

**Comment by stasm** [comment]
Renaming makes sense to me.

There haven't been any changes fo fluent-langneg on master since its 0.1.0 release. I think it should then OK to `npm deprecate` it and publish `fluent-locale` 0.1.0. We'll need to update the docs and the dependecies in examples, too, but that's trivial.

**Comment by stasm** [comment]
Or, we could first publish `fluent-langneg` 0.1.1 and deprecate _that_. This way the current users of 0.1.0 won't notice the change.

**Comment by stasm** [comment]
`fluent-langneg` has been renamed to `@fluent/langneg`. I verified with @zbraniecki that we should keep the `langneg` part in the name. Closing this issue.
