### ISSUE TITLE
Allow ? as part of the identifier

### ISSUE THREAD

**Issue by stasm** [projectfluent/fluent.js#84]
In https://github.com/projectfluent/fluent/pull/51 the syntax was changed to only forbid `?` at the start of `Identifiers`.

**Comment by zbraniecki** [comment]
can we consider forbidding "?" as a character in the identifier? I don't see a solid reason to remove another sygil from the pool of available ones for the future, and I haven't seen any developer trying to use "?" in ids so far.

**Comment by stasm** [comment]
As I explained in https://github.com/projectfluent/fluent/issues/49#issuecomment-314433325 I would like to encourage things like:

```
delete-all-files? = Really delete all files?
```

Hopefully we won't be adding more sigils to the syntax. I'm working towards _removing_ them instead. Do you have a particular idea that would benefit from `?` being an illegal character in identifiers?

**Comment by zbraniecki** [comment]
> Do you have a particular idea that would benefit from ? being an illegal character in identifiers?

No :) And I'm very happy that I don't! But having to have a use case in mind in order to justify not extending ID's to claim it is a high barrier which I hope is not required.

> `delete-all-files? = Really delete all files?`

Why not:

`delete-all-files = Really delete all files?`

I feel like no engineer using Fluent would start by thinking about placing a question mark in the ID. Is there a chance to start by not allowing it and if we see people trying or requesting it, we can easily add it?

**Comment by zbraniecki** [comment]
Otherwise, it seems inconsistent not to allow for:
`hello-world! = Hello World!`

or
`i'm-sorry,did-you-knock? = I'm sorry, did you knock?`

**Comment by zbraniecki** [comment]
And since we're an intl project:

```
¡hola-amigo! = ¡Hola, amigo!
¿como-estas? = ¿Cómo estás?
```

:D

**Comment by Pike** [comment]
> delete-all-files? = Really delete all files?

I think this is hard to explain and tell apart from the "use english strings as keys". And I consider actual English text as keys to be bad.

The way I like to talk about message IDs is to choose good variable names. Hyphens stretch that, but actual grammatical punctuation does break that, I think.

**Comment by stasm** [comment]
We already had this discussion in https://github.com/projectfluent/fluent/issues/49. I'll respond here but if you feel strongly about this and would like to continue, please do so in a new issue in the Fluent Syntax repo.

This is not about using English punctuation in identifiers but rather about communicating the role of the message better. Software inherently ends up asking questions via the UI. Allowing the question mark in identifiers makes it easier to communicate the intent without thinking too much about naming conflicts.

Instead of using longer ids like `delete-all-prompt` or `delete-all-confirm`, it allows for this:

```
delete-all? = Really delete all files?
delete-all = Yes, delete all files.
```

For this reason, question mark is in fact a valid character in identifiers in many languages. I know of at least Clojure, Elixir, Ruby and Scala that allow it.

We've also seen developer try using the question mark in Gaia. I found examples similar to the following one in the localizations of the [Camera](https://hg.mozilla.org/gaia-l10n/en-US/file/tip/apps/gallery/gallery.properties#l9), Dialer, Gallery, and Videos apps:

```
delete-photo? = Delete photo?
delete-video? = Delete video?
```

This is one of those things that I don't think developers will actively ask us to introduce but they might appreciate it if it's there. If you feel strongly about forbidding the question mark (at least right now), please file a new issue in the Fluent Syntax repo.

**Comment by stasm** [comment]
Closing this as per https://github.com/projectfluent/fluent/issues/65.
