### ISSUE TITLE
[fluent-react] examples not running

### ISSUE THREAD

**Issue by hkasemir** [projectfluent/fluent.js#93]
str: 

clone fluent, go to fluent-react examples folder, `npm i` and `npm start`

the resulting page is blank with the following console error:
![image](https://user-images.githubusercontent.com/10947914/32757265-7afd916a-c893-11e7-87c0-5a671fa500f8.png)

**Comment by zbraniecki** [comment]
I was able to reproduce it on `hello-world` example. My log:

```
16:06:39.207 Download the React DevTools for a better development experience: https://fb.me/react-devtools
ReactDOM.js:71
16:06:39.213 Intl.PluralRules already exists, and has NOT been replaced by this polyfill
compat.js:817
16:06:39.213 To force, set a global ClobberIntlPluralRules = true
compat.js:818
16:06:39.234
TypeError: context.messages.has is not a function
[Więcej informacji]
compat.js:100
```

**Comment by stasm** [comment]
The culprit are the outdated dependencies defined in the examples' `package.json` files.

I suggest we always use local dependencies in the examples via the `file:` version range. See https://docs.npmjs.com/files/package.json#dependencies.
